# Generated by Django 6.0.3 on 2026-06-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Удалено в'),
        ),
    ]
