
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Layout
    'nav.dashboard': 'Main Page',
    'nav.analytics': 'Analytics',
    'nav.quick_input': 'Data Entry',
    'nav.kitchens': 'Kitchens',
    'nav.products': 'Products',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.logout': 'Log out',
    'nav.main_menu': 'Main Menu',
    'nav.explore': 'Explore',
    'header.greeting': 'Good Afternoon, Chef',
    'header.role': 'Head Chef',
    
    // Dashboard
    'dash.total_revenue': 'Total Sales Revenue',
    'dash.revenue_period': 'Revenue in period',
    'dash.incoming_vol': 'Incoming Volume',
    'dash.units_received': 'Units received',
    'dash.sales_count': 'Sales Count',
    'plan.upgrade_cta': 'Upgrade to Pro',
    'plan.history_limit': 'Basic plan shows the last 30 days of history. Pro has no limits.',
    'plan.pro_feature.title': 'Available in Pro',
    'plan.pro_feature.product_chart': 'The product analytics chart is available on the Pro plan.',
    'plan.upsell.later': 'Later',
    'plan.limit_near': 'Kitchen limit almost reached',
    'plan.limit_reached': 'Kitchen limit reached',
    'plan.limit_near_users': 'Team member limit almost reached',
    'plan.limit_reached_users': 'Team member limit reached',
    'dash.no_data': 'No data for this period',
    'dash.no_data.hint': 'Pick another date range or add operations in Quick Input.',
    'dash.transactions': 'Transactions',
    'dash.operations': 'Operations',
    'dash.total_events': 'Total logged events',
    'dash.trends': 'Transaction Trends',
    'dash.profit_summary': 'Profit Summary',
    'dash.see_details': 'See Details',
    'dash.yearly_profit': 'Yearly Project Profit',
    'dash.weekly_profit': 'Weekly Project Profit',
    'dash.filter.daily': 'Daily',
    'dash.filter.monthly': 'Monthly',
    'dash.filter.all_kitchens': 'All Kitchens',
    'dash.avg_yearly': 'Avg yearly',
    'dash.avg_monthly': 'Avg monthly',
    'dash.from': 'From',
    'dash.main_table': 'Main Table',
    'dash.sales_cost_dynamics': 'Sales and Purchases',

    // Quick Input
    'qi.title': 'Data Entry',
    'qi.op.incoming': 'Incoming',
    'qi.op.daily': 'Stock',
    'qi.op.transfer': 'Transfer',
    'qi.op.sale': 'Sale',
    'qi.date': 'Date',
    'qi.kitchen': 'Kitchen',
    'qi.from_kitchen': 'From Kitchen',
    'qi.to_kitchen': 'To Kitchen',
    'qi.product': 'Product',
    'qi.product_ph': 'Scan code or type name...',
    'qi.qty': 'Quantity',
    'qi.balance': 'Balance',
    'qi.price': 'Unit Price',
    'qi.revenue': 'Revenue (Unit)',
    'qi.total_calc': 'Total',
    'qi.save': 'Save',
    'qi.history': 'Recent History',
    'qi.search_ph': 'Search product...',
    'qi.all_types': 'All Types',
    'qi.all_kitchens': 'All Kitchens',
    'qi.not_found': 'Not found',
    'qi.no_history': 'No history found matching filters.',
    'qi.unit': 'Unit',
    'qi.total_count': 'Total Entries',
    'qi.total_amount': 'Total Sum',

    // Kitchens
    'kit.add': 'Add Kitchen',
    'kit.search_ph': 'Search kitchen...',
    'kit.name': 'Kitchen Name',
    'kit.status': 'Status',
    'kit.actions': 'Actions',
    'kit.active': 'Active',
    'kit.inactive': 'Inactive',
    'kit.no_data': 'No kitchens found matching your criteria.',
    'kit.modal.edit': 'Edit Kitchen',
    'kit.modal.add': 'Add New Kitchen',
    'kit.modal.status_label': 'Operational Status',
    'kit.modal.status_desc': 'Enable or disable this kitchen location',
    'kit.create': 'Create Kitchen',
    'kit.update': 'Update Kitchen',
    'kit.delete_confirm': 'Are you sure you want to delete this kitchen?',

    // Products
    'prod.add': 'Add Product',
    'prod.search_ph': 'Search product name or code...',
    'prod.code': 'Code',
    'prod.name': 'Product Name',
    'prod.category': 'Category',
    'prod.unit': 'Unit',
    'prod.no_data': 'No products found.',
    'prod.modal.edit': 'Edit Product',
    'prod.modal.add': 'Add New Product',
    'prod.create': 'Create Product',
    'prod.update': 'Update Product',
    'prod.delete_title': 'Delete Product',
    'prod.delete_confirm': 'Delete this product? Operations history will remain.',
    'prod.cat.all': 'All',

    // Analytics
    'anl.kitchen_branch': 'Kitchen / Branch',
    'anl.apply': 'Apply Filters',
    'anl.export': 'Export Excel',
    'anl.dept_analytics': 'Department Analytics',
    'anl.sales_dynamics': 'Sales Dynamics',
    'anl.col.dept': 'Dept',
    'anl.col.start': 'Start bal.',
    'anl.col.in': 'Income',
    'anl.col.exp': 'Expense',
    'anl.col.end': 'End bal.',
    'anl.col.sales': 'Sales(sum)',
    'anl.col.mrk': 'Margin(sum)',
    'anl.col.trns': 'Transfer',
    'anl.col.trns_in': 'Trns(In)',
    'anl.col.trns_out': 'Trns(Out)',
    'anl.col.dept.full': 'Department',
    'anl.col.start.full': 'Beginning Balance',
    'anl.col.in.full': 'Incoming',
    'anl.col.exp.full': 'Expense',
    'anl.col.end.full': 'Ending Balance',
    'anl.col.sales.full': 'Sales (sum)',
    'anl.col.mrk.full': 'Margin',
    'anl.col.trns.full': 'Transfers',
    'anl.col.trns_in.full': 'Transfers (In)',
    'anl.col.trns_out.full': 'Transfers (Out)',
    'anl.total': 'TOTAL',
    'anl.date_from': 'Date From',
    'anl.date_to': 'Date To',

    // Reports
    'rep.title': 'Inventory Balance Report',
    'rep.col.code': 'Code',
    'rep.col.product': 'Product Name',
    'rep.col.incoming': 'Incoming',
    'rep.col.sales': 'Sales',
    'rep.col.transfer': 'Transfer (Net)',
    'rep.col.balance': 'Current Balance',
    'rep.no_data': 'No data found for this period.',
    'rep.qty': 'Qty',
    'rep.sum': 'Sum',

    // Login
    'auth.welcome': 'Welcome Back',
    'auth.subtitle': 'MARGA MANAGER',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.signin': 'Sign In',
    'auth.error': 'Invalid username or password.',
    'auth.creds': 'Default credentials:',
    'register.title': 'Start 14 days free',
    'register.subtitle': 'Create your organization and enter the cabinet.',
    'register.organization': 'Organization name',
    'register.owner': 'Your name',
    'register.phone': 'Phone number',
    'register.submit': 'Create account',
    'register.error': 'Could not register. Check the fields and try again.',
    'register.have_account': 'Already have access?',
    'register.no_account': 'No account yet?',
    'onboarding.title': 'Add your first branch',
    'onboarding.subtitle': 'This is enough to start entering stock, sales, and daily work.',
    'onboarding.branch': 'Branch or workshop name',
    'onboarding.branch_default': 'Main branch',
    'onboarding.submit': 'Start work',
    'onboarding.error': 'Could not create branch.',

    // Landing
    'landing.login': 'Sign in',
    'landing.badge': 'For owners of cafes, workshops, and branches',
    'landing.hero.title': 'Easily manage staff and warehouse stock',
    'landing.hero.subtitle': 'MARGA MANAGER brings order to stock records and makes the work rules between the owner and staff clear.',
    'landing.hero.audience': 'For cafes, pastry shops, and small production businesses that need simple daily control.',
    'landing.cta.open': 'Start 14 days free',
    'landing.cta.inside': 'How it works',
    'landing.snapshot.title': 'What the owner sees',
    'landing.snapshot.subtitle': 'The main work picture for the day',
    'landing.snapshot.status': 'Now',
    'landing.metric.margin': 'Daily margin',
    'landing.metric.margin.value': '4.2 mln',
    'landing.metric.sales': 'Sales and cost',
    'landing.metric.sales.value': '+18%',
    'landing.metric.stock': 'Raw stock',
    'landing.metric.stock.value': '126 kg',
    'landing.row.margin': 'Gross income (margin)',
    'landing.row.margin.value': '1 240 000',
    'landing.row.dynamics': 'Sales and cost dynamics',
    'landing.row.dynamics.value': '+18%',
    'landing.row.stock': 'Raw material stock',
    'landing.row.stock.value': '126 kg',
    'landing.row.expense': 'Raw material expense',
    'landing.row.expense.value': '870 000',
    'landing.row.departments': 'Department daily results',
    'landing.row.departments.value': '3 depts',
    'landing.module.input.title': 'Fast entry',
    'landing.module.input.text': 'Staff quickly enters incoming goods, stock, transfers, and sales. The owner sees it in a clear form, not in scattered messages.',
    'landing.quick.incoming': 'Incoming',
    'landing.quick.incoming.text': 'Add deliveries quickly.',
    'landing.quick.stock': 'Stock',
    'landing.quick.stock.text': 'See what remains.',
    'landing.quick.sales': 'Sales',
    'landing.quick.sales.text': 'Record daily sales.',
    'landing.price.basic': 'Basic plan',
    'landing.price.basic.note': 'For simple daily control',
    'landing.price.pro': 'Pro plan',
    'landing.price.pro.note': 'For growing teams and branches',
    'landing.price.trial': '14 days free',
    'landing.module.rules.title': 'Order in daily work',
    'landing.module.rules.text': 'Each person has their own access. It is easier to see who did what and who is responsible for each step.',
    'landing.module.branches.title': 'Branches and products',
    'landing.module.branches.text': 'Products, units, kitchens, workshops, and branches can be checked in one place.',
    'landing.module.saas.title': 'Payments and access',
    'landing.module.saas.text': 'You can manage tariffs, users, payments, and access time without manual confusion.',
    'landing.saas.title': 'Ready for different clients',
    'landing.saas.text': 'Each client works separately with their own data, staff, branches, and payments.',
    'landing.saas.item.tenancy': 'Client data is separated',
    'landing.saas.item.auth': 'Login and password access',
    'landing.saas.item.limits': 'Tariff limits',
    'landing.saas.item.audit': 'Payment and change history',
    'landing.roles.title': 'Each person sees only their part',
    'landing.role.super.title': 'Service owner',
    'landing.role.super': 'manages clients, tariffs, and main settings',
    'landing.role.admin.title': 'Business manager',
    'landing.role.admin': 'manages branches, products, staff, reports, and payments',
    'landing.role.kitchen.title': 'Staff member',
    'landing.role.kitchen': 'quickly enters daily data without extra settings',
    'landing.footer.title': 'Start with simple control',
    'landing.footer.text': 'Open the dashboard and see how stock, staff, and daily work stay in order.',
    'landing.footer.roles': '3 access levels',
    'landing.footer.devices': 'Computer + phone',
    'landing.nav.features': 'Features',
    'landing.nav.pricing': 'Pricing',
    'landing.cta.note': 'No card required — cancel anytime',
    'landing.pain.title': 'Sound familiar?',
    'landing.pain.before.label': 'Now — in a notebook',
    'landing.pain.after.label': 'In Marga Manager',
    'landing.pain.1.before': 'Records live in notebooks and chat messages',
    'landing.pain.1.after': 'Every operation in one system with history',
    'landing.pain.2.before': 'Stock is counted by hand once a week',
    'landing.pain.2.after': 'Daily stock and expense for every kitchen',
    'landing.pain.3.before': 'No idea where the margin goes',
    'landing.pain.3.after': 'Markup and cost are calculated automatically',
    'landing.steps.title': 'How it works',
    'landing.steps.1.title': 'Sign up',
    'landing.steps.1.text': 'Create an account and your organization in a couple of minutes.',
    'landing.steps.2.title': 'Add products and kitchens',
    'landing.steps.2.text': 'Set up your catalog, units, and branches once.',
    'landing.steps.3.title': 'Team enters daily data',
    'landing.steps.3.text': 'Incoming, stock, and sales — you see reports in real time.',
    'landing.pricing.title': 'Pricing',
    'landing.pricing.subtitle': 'Start free for 14 days, then pick a plan. Payment via Payme.',
    'landing.price.period': '/month',
    'landing.price.popular': 'Popular',
    'landing.price.basic.f1': '1 kitchen or branch',
    'landing.price.basic.f2': 'Up to 10 team members',
    'landing.price.basic.f3': 'All operation types and reports',
    'landing.price.basic.f4': 'Excel export anytime',
    'landing.price.pro.f1': '10 kitchens or branches',
    'landing.price.pro.f2': 'Up to 50 team members',
    'landing.price.pro.f3': 'Everything in Basic',
    'landing.price.pro.f4': 'For chains and growing teams',
    'landing.testimonials.title': 'What owners say',
    'landing.faq.title': 'Frequently asked questions',
    'landing.faq.q1': 'How fast can we start?',
    'landing.faq.a1': 'Registration takes a couple of minutes: create an account, add products and kitchens, and the team can enter data the same day.',
    'landing.faq.q2': 'Do I need a card for the trial?',
    'landing.faq.a2': 'No. The first 14 days are free without a card. After the trial you choose a plan and pay via Payme.',
    'landing.faq.q3': 'Who can see my data?',
    'landing.faq.a3': 'Each organization works with its own isolated data. Access is limited to your staff by roles.',
    'landing.faq.q4': 'Can I export my data?',
    'landing.faq.a4': 'Yes, reports and operation history can be exported to Excel at any time.',

    // SaaS
    'saas.plan.basic': 'Basic Plan',
    'saas.plan.pro': 'Pro Plan',
    'saas.limit_reached': 'Kitchen Limit Reached',
    'saas.limit_desc': 'You have reached the limit of 1 kitchen on the Basic plan.',
    'saas.upgrade_title': 'Upgrade to Pro',
    'saas.upgrade_desc': 'Get unlimited kitchens and advanced features with the Pro plan.',
    'saas.upgrade_btn': 'Upgrade to Pro',
    'saas.current_usage': 'Usage',
    'saas.unlimited': 'Unlimited',
    'saas.basic_features': '1 Kitchen limit',
    'saas.pro_features': 'Unlimited Kitchens',

    // Settings & Billing
    'set.title': 'Settings',
    'set.tab.general': 'General',
    'set.tab.users': 'Team Members',
    'set.tab.billing': 'Plans & Billing',
    'set.users.add': 'Add Member',
    'set.users.role': 'Role',
    'set.users.role.admin': 'Manager (Admin)',
    'set.users.role.kitchen': 'Kitchen Staff',
    'set.users.fullname': 'Full Name',
    'set.users.username': 'Username',
    'set.users.password': 'Password',
    'set.users.delete_confirm': 'Are you sure you want to remove this user?',
    'set.users.limit': 'User limit reached',
    'set.users.desc': 'Manage who has access to your organization workspace.',
    
    // Settings General
    'set.gen.profile': 'Organization Profile',
    'set.gen.org_name': 'Restaurant Name',
    'set.gen.phone': 'Phone Number',
    'set.gen.email': 'Email Address',
    'set.gen.address': 'Physical Address',
    'set.gen.finance': 'Finance & Region',
    'set.gen.currency': 'Currency',
    'set.gen.tax': 'Tax Rate (%)',
    'set.gen.inventory': 'Inventory Rules',
    'set.gen.low_stock': 'Low Stock Threshold',
    'set.gen.save': 'Save Changes',
    'set.gen.saved': 'Settings saved successfully',

    // Billing
    'bill.free': 'Free',
    'bill.current': 'Current Plan',
    'bill.cycle': '/ month',
    'bill.feature.kitchens': 'Kitchens',
    'bill.feature.users': 'Users',
    'bill.feature.dailyReports': 'Daily owner reports',
    'bill.feature.analytics': 'Advanced Analytics',
    'bill.feature.support': 'Priority Support',
    'bill.btn.upgrade': 'Upgrade',
    'bill.btn.downgrade': 'Downgrade',
    'bill.btn.current': 'Current Plan',
    'bill.btn.renew': 'Renew',
    'bill.modal.title': 'Confirm Subscription Change',
    'bill.modal.desc': 'You are about to switch your subscription plan.',
    'bill.modal.new_plan': 'New Plan',
    'bill.modal.price': 'Price',
    'bill.modal.total': 'Total due today',
    'bill.modal.confirm': 'Confirm & Pay',
    'bill.modal.processing': 'Processing...',
    'bill.pay_now': 'Pay now',

    // Common
    'common.show': 'Show',
    'common.entries': 'entries',
    'common.prev': 'Previous',
    'common.next': 'Next',
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',

    // QuickInput modal/edit
    'qi.edit_entry': 'Edit Entry',
    'qi.time': 'Time',
    'qi.product_details': 'Product Details',
    'qi.unit_price': 'Unit Price',
    'qi.total_price': 'Total Price',
    'qi.save_changes': 'Save Changes',
    'qi.confirm_delete': 'Confirm Delete',
    'qi.delete_op_msg': 'Are you sure you want to delete this operation? This action cannot be undone.',

    // Settings billing
    'set.billing.desc': 'Manage your subscription and billing details.',
    'set.billing.trial': 'New clients get 14 days free.',
    'set.billing.history': 'Payment History',
    'set.billing.th_date': 'Date',
    'set.billing.th_plan': 'Plan',
    'set.billing.th_amount': 'Amount',
    'set.billing.th_status': 'Status',
    'set.billing.recommended': 'Recommended',

    // Settings profile
    'set.profile.identity': 'Identity & Contact',
    'set.threshold_help': 'Setting this threshold highlights low-stock products in reports.',

    // Chart
    'dash.chart.daily': 'Daily',
    'dash.chart.cumulative': 'Cumulative',
    'dash.chart.sales': 'Sales',
    'dash.chart.cost': 'Purchases',
    'dash.chart.cum_sales': 'Cumulative Sales',
    'dash.chart.cum_cost': 'Cumulative Purchases',
    'dash.chart.product': 'By Product',
    'dash.chart.prod_expense': 'Product consumption',
    'dash.chart.margin': 'Daily difference',
    'dash.chart.prod_hint': 'Consumption is calculated on days when a stock balance was recorded.',

    // Products — category modal
    'prod.manage_cat': 'Manage Categories',
    'prod.new_cat_placeholder': 'New Category Name...',

    // Kitchens — plan upsell
    'kit.pro_plan_includes': 'Pro Plan Includes:',
    'kit.feature.analytics': 'Advanced Analytics (Coming Soon)',
    'kit.feature.priority': 'Priority Support',

    // Login — demo block
    'login.demo_creds': 'Demo Credentials',
    'login.client_admin': 'Client Admin',
    'login.kitchen_staff': 'Kitchen Staff',
    'login.access_limited': 'Limited access',
    // Subscription expiry banner
    'subscription.expiring_soon': 'Your plan expires on {date}. Renew now.',
    'subscription.expired': 'Your plan has expired. Renew now.',
    'subscription.renew_now': 'Renew',
    // Admin panel
    'admin.suspend': 'Suspend',
    'admin.unsuspend': 'Activate',
    'admin.suspend_confirm': 'Suspend this organization?',
    'admin.org_detail': 'Organization Detail',
    'admin.audit_log': 'Audit Log',
    'admin.audit.all_events': 'All event types',
    'admin.audit.all_orgs': 'All organizations',
    'admin.plans_tab': 'Plans',
    'admin.m.tenants': 'Total Tenants',
    'admin.m.mrr': 'MRR (UZS)',
    'admin.m.active': 'Active Rate',
    'admin.m.licensed': 'Licensed Users',
    'admin.orgs': 'Organizations',
    'admin.new_tenant': 'New Tenant',
    'admin.search_tenants': 'Search tenants...',
    'admin.act.users': 'Manage Users',
    'admin.act.edit': 'Edit',
    'admin.act.suspend': 'Suspend',
    'admin.act.activate': 'Activate',
    'admin.act.delete': 'Delete',
    'prod.btn.categories': 'Categories',
    'admin.event_type': 'Event Type',
    'admin.actor': 'Actor',
    'admin.target': 'Target',
    'admin.old_value': 'Old',
    'admin.new_value': 'New',
    'admin.kitchens_tab': 'Kitchens',
    'admin.products_tab': 'Products',
    'admin.users_tab': 'Users',
    'admin.payments_tab': 'Payments',
    'admin.edit_tab': 'Edit',
    'admin.org_suspended': 'Organization is suspended',
    'access.suspended.title': 'Access limited',
    'access.suspended.text': 'Access is temporarily limited. Choose a plan to continue, or contact the owner or administrator.',
    'access.suspended.pay_title': 'Continue with a plan',
    'access.suspended.pay_error': 'Could not open payment. Try again later.',
    'access.suspended.logout': 'Log out',
  },
  ru: {
    // Navigation & Layout
    'nav.dashboard': 'Главная',
    'nav.analytics': 'Аналитика',
    'nav.quick_input': 'Ввод данных',
    'nav.kitchens': 'Кухни',
    'nav.products': 'Продукты',
    'nav.reports': 'Отчеты',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
    'nav.main_menu': 'Главное меню',
    'nav.explore': 'Разное',
    'header.greeting': 'Добрый день, Шеф',
    'header.role': 'Шеф-повар',

    // Dashboard
    'dash.total_revenue': 'Общая выручка',
    'dash.revenue_period': 'Выручка за период',
    'dash.incoming_vol': 'Объем прихода',
    'dash.units_received': 'Единиц получено',
    'dash.sales_count': 'Кол-во продаж',
    'plan.upgrade_cta': 'Перейти на Pro',
    'plan.history_limit': 'Тариф Basic показывает историю за последние 30 дней. В Pro — без ограничений.',
    'plan.pro_feature.title': 'Доступно в Pro',
    'plan.pro_feature.product_chart': 'График аналитики по продуктам доступен на тарифе Pro.',
    'plan.upsell.later': 'Позже',
    'plan.limit_near': 'Лимит кухонь почти исчерпан',
    'plan.limit_reached': 'Достигнут лимит кухонь',
    'plan.limit_near_users': 'Лимит сотрудников почти исчерпан',
    'plan.limit_reached_users': 'Достигнут лимит сотрудников',
    'dash.no_data': 'Нет данных за период',
    'dash.no_data.hint': 'Выберите другой диапазон дат или добавьте операции во «Вводе данных».',
    'dash.transactions': 'Транзакции',
    'dash.operations': 'Операции',
    'dash.total_events': 'Всего записей',
    'dash.trends': 'Тренд транзакций',
    'dash.profit_summary': 'Сводка по прибыли',
    'dash.see_details': 'Подробнее',
    'dash.yearly_profit': 'Годовая прибыль',
    'dash.weekly_profit': 'Недельная прибыль',
    'dash.filter.daily': 'День',
    'dash.filter.monthly': 'Месяц',
    'dash.filter.all_kitchens': 'Все кухни',
    'dash.avg_yearly': 'Сред. год',
    'dash.avg_monthly': 'Сред. месяц',
    'dash.from': 'С',
    'dash.main_table': 'Главная таблица',
    'dash.sales_cost_dynamics': 'Продажи и закупки',

    // Quick Input
    'qi.title': 'Ввод данных',
    'qi.op.incoming': 'Приход',
    'qi.op.daily': 'Остаток',
    'qi.op.transfer': 'Перевод',
    'qi.op.sale': 'Продажа',
    'qi.date': 'Дата',
    'qi.kitchen': 'Кухня',
    'qi.from_kitchen': 'Из кухни',
    'qi.to_kitchen': 'В кухню',
    'qi.product': 'Продукт',
    'qi.product_ph': 'Сканируйте или введите имя...',
    'qi.qty': 'Количество',
    'qi.balance': 'Баланс',
    'qi.price': 'Цена за ед.',
    'qi.revenue': 'Цена (ед.)',
    'qi.total_calc': 'Итого',
    'qi.save': 'Сохранить',
    'qi.history': 'Недавняя история',
    'qi.search_ph': 'Поиск продукта...',
    'qi.all_types': 'Все типы',
    'qi.all_kitchens': 'Все кухни',
    'qi.not_found': 'Не найдено',
    'qi.no_history': 'История не найдена по фильтрам.',
    'qi.unit': 'Ед.',
    'qi.total_count': 'Всего записей',
    'qi.total_amount': 'Итого сумма',

    // Kitchens
    'kit.add': 'Добавить кухню',
    'kit.search_ph': 'Поиск кухни...',
    'kit.name': 'Название кухни',
    'kit.status': 'Статус',
    'kit.actions': 'Действия',
    'kit.active': 'Активен',
    'kit.inactive': 'Неактивен',
    'kit.no_data': 'Кухни не найдены.',
    'kit.modal.edit': 'Редактировать кухню',
    'kit.modal.add': 'Новая кухня',
    'kit.modal.status_label': 'Статус работы',
    'kit.modal.status_desc': 'Включить или отключить эту точку',
    'kit.create': 'Создать',
    'kit.update': 'Обновить',
    'kit.delete_confirm': 'Вы уверены, что хотите удалить эту кухню?',

    // Products
    'prod.add': 'Добавить продукт',
    'prod.search_ph': 'Поиск по имени или коду...',
    'prod.code': 'Код',
    'prod.name': 'Название',
    'prod.category': 'Категория',
    'prod.unit': 'Ед. изм.',
    'prod.no_data': 'Продукты не найдены.',
    'prod.modal.edit': 'Редактировать продукт',
    'prod.modal.add': 'Новый продукт',
    'prod.create': 'Создать',
    'prod.update': 'Обновить',
    'prod.delete_title': 'Удалить продукт',
    'prod.delete_confirm': 'Удалить продукт? История операций сохранится.',
    'prod.cat.all': 'Все',

    // Analytics
    'anl.kitchen_branch': 'Кухня / Филиал',
    'anl.apply': 'Применить',
    'anl.export': 'Экспорт Excel',
    'anl.dept_analytics': 'Аналитика отделов',
    'anl.sales_dynamics': 'Динамика продаж',
    'anl.col.dept': 'Отдел',
    'anl.col.start': 'Нач. остаток',
    'anl.col.in': 'Приход',
    'anl.col.exp': 'Расход',
    'anl.col.end': 'Кон. остаток',
    'anl.col.sales': 'Продажи(сум)',
    'anl.col.mrk': 'Маржа(сум)',
    'anl.col.trns': 'Перевод',
    'anl.col.trns_in': 'Пер(Прих)',
    'anl.col.trns_out': 'Пер(Расх)',
    'anl.col.dept.full': 'Отдел',
    'anl.col.start.full': 'Начальный остаток',
    'anl.col.in.full': 'Приход',
    'anl.col.exp.full': 'Расход',
    'anl.col.end.full': 'Конечный остаток',
    'anl.col.sales.full': 'Продажи (сумма)',
    'anl.col.mrk.full': 'Маржа',
    'anl.col.trns.full': 'Переводы',
    'anl.col.trns_in.full': 'Переводы (Приход)',
    'anl.col.trns_out.full': 'Переводы (Расход)',
    'anl.total': 'ИТОГО',
    'anl.date_from': 'Дата с',
    'anl.date_to': 'Дата по',

    // Reports
    'rep.title': 'Отчет по остаткам',
    'rep.col.code': 'Код',
    'rep.col.product': 'Продукт',
    'rep.col.incoming': 'Приход',
    'rep.col.sales': 'Продажи',
    'rep.col.transfer': 'Переводы (Нетто)',
    'rep.col.balance': 'Текущий остаток',
    'rep.no_data': 'Данных за этот период не найдено.',
    'rep.qty': 'Кол-во',
    'rep.sum': 'Сумма',

    // Login
    'auth.welcome': 'С возвращением',
    'auth.subtitle': 'MARGA MANAGER',
    'auth.username': 'Имя пользователя',
    'auth.password': 'Пароль',
    'auth.signin': 'Войти',
    'auth.error': 'Неверный логин или пароль.',
    'auth.creds': 'Доступы по умолчанию:',
    'register.title': 'Начать 14 дней бесплатно',
    'register.subtitle': 'Создайте организацию и войдите в кабинет.',
    'register.organization': 'Название организации',
    'register.owner': 'Ваше имя',
    'register.phone': 'Номер телефона',
    'register.submit': 'Создать аккаунт',
    'register.error': 'Не удалось зарегистрироваться. Проверьте поля и попробуйте ещё раз.',
    'register.have_account': 'Уже есть доступ?',
    'register.no_account': 'Ещё нет аккаунта?',
    'onboarding.title': 'Добавьте первый филиал',
    'onboarding.subtitle': 'Этого достаточно, чтобы начать вводить остатки, продажи и ежедневную работу.',
    'onboarding.branch': 'Название филиала или цеха',
    'onboarding.branch_default': 'Основной филиал',
    'onboarding.submit': 'Начать работу',
    'onboarding.error': 'Не удалось создать филиал.',

    // Landing
    'landing.login': 'Войти',
    'landing.badge': 'Для владельцев кафе, цехов и филиалов',
    'landing.hero.title': 'Легко управляйте персоналом и складскими остатками',
    'landing.hero.subtitle': 'MARGA MANAGER наводит порядок в складском учёте и помогает выстроить понятные правила работы между владельцем и персоналом.',
    'landing.hero.audience': 'Подходит для кафе, кондитерских цехов и небольших производств, где важно быстро видеть работу команды и движение товаров.',
    'landing.cta.open': 'Начать 14 дней бесплатно',
    'landing.cta.inside': 'Как это работает',
    'landing.snapshot.title': 'Что видит владелец',
    'landing.snapshot.subtitle': 'Главное по работе за день',
    'landing.snapshot.status': 'Сейчас',
    'landing.metric.margin': 'Маржа за день',
    'landing.metric.margin.value': '4.2 млн',
    'landing.metric.sales': 'Продажи и себестоимость',
    'landing.metric.sales.value': '+18%',
    'landing.metric.stock': 'Сырьё',
    'landing.metric.stock.value': '126 кг',
    'landing.row.margin': 'Ежедневная валовая прибыль (маржа)',
    'landing.row.margin.value': '1 240 000',
    'landing.row.dynamics': 'Динамика продаж и себестоимости',
    'landing.row.dynamics.value': '+18%',
    'landing.row.stock': 'Ежедневные остатки сырья',
    'landing.row.stock.value': '126 кг',
    'landing.row.expense': 'Ежедневный расход сырья',
    'landing.row.expense.value': '870 000',
    'landing.row.departments': 'Результаты отделов за день',
    'landing.row.departments.value': '3 отдела',
    'landing.module.input.title': 'Быстрый ввод',
    'landing.module.input.text': 'Сотрудник быстро вносит приход, остатки, перемещения и продажи. Владелец видит всё в понятном виде, а не в разрозненных сообщениях.',
    'landing.quick.incoming': 'Приход',
    'landing.quick.incoming.text': 'Быстро внесите новые товары.',
    'landing.quick.stock': 'Остатки',
    'landing.quick.stock.text': 'Сразу видно, что осталось.',
    'landing.quick.sales': 'Продажи',
    'landing.quick.sales.text': 'Записывайте продажи за день.',
    'landing.price.basic': 'Basic тариф',
    'landing.price.basic.note': 'Для простого ежедневного контроля',
    'landing.price.pro': 'Pro тариф',
    'landing.price.pro.note': 'Для команды и нескольких точек',
    'landing.price.trial': '14 дней бесплатно',
    'landing.module.rules.title': 'Порядок в работе',
    'landing.module.rules.text': 'У каждого сотрудника свой доступ. Легче понять, кто что сделал и кто за что отвечает.',
    'landing.module.branches.title': 'Филиалы и продукты',
    'landing.module.branches.text': 'Можно следить за продуктами, остатками, кухнями, цехами и филиалами в одном месте.',
    'landing.module.saas.title': 'Оплата и доступ',
    'landing.module.saas.text': 'Можно управлять тарифами, пользователями, оплатой и сроком доступа без ручной путаницы.',
    'landing.saas.title': 'Готово для разных клиентов',
    'landing.saas.text': 'Каждый клиент работает отдельно со своими данными, сотрудниками, филиалами и оплатой.',
    'landing.saas.item.tenancy': 'Данные клиентов разделены',
    'landing.saas.item.auth': 'Вход по логину и паролю',
    'landing.saas.item.limits': 'Ограничения по тарифу',
    'landing.saas.item.audit': 'История оплат и изменений',
    'landing.roles.title': 'Каждый видит только своё',
    'landing.role.super.title': 'Владелец сервиса',
    'landing.role.super': 'управляет клиентами, тарифами и основными настройками',
    'landing.role.admin.title': 'Управляющий бизнесом',
    'landing.role.admin': 'управляет филиалами, продуктами, сотрудниками, отчётами и оплатой',
    'landing.role.kitchen.title': 'Сотрудник',
    'landing.role.kitchen': 'быстро вносит ежедневные данные без доступа к лишним настройкам',
    'landing.footer.title': 'Начните с простого контроля',
    'landing.footer.text': 'Откройте кабинет и посмотрите, как склад, сотрудники и ежедневная работа остаются в порядке.',
    'landing.footer.roles': '3 уровня доступа',
    'landing.footer.devices': 'Компьютер + телефон',
    'landing.nav.features': 'Возможности',
    'landing.nav.pricing': 'Тарифы',
    'landing.cta.note': 'Банковская карта не нужна — отмена в любой момент',
    'landing.pain.title': 'Знакомые проблемы?',
    'landing.pain.before.label': 'Сейчас — в тетради',
    'landing.pain.after.label': 'В Marga Manager',
    'landing.pain.1.before': 'Учёт ведётся в тетрадях и чатах',
    'landing.pain.1.after': 'Все операции в одной системе с историей',
    'landing.pain.2.before': 'Остатки считаются вручную раз в неделю',
    'landing.pain.2.after': 'Ежедневные остатки и расход по каждой кухне',
    'landing.pain.3.before': 'Непонятно, куда уходит маржа',
    'landing.pain.3.after': 'Наценка и себестоимость считаются автоматически',
    'landing.steps.title': 'Как это работает',
    'landing.steps.1.title': 'Зарегистрируйтесь',
    'landing.steps.1.text': 'Создайте аккаунт и организацию за пару минут.',
    'landing.steps.2.title': 'Добавьте продукты и кухни',
    'landing.steps.2.text': 'Один раз заполните справочник, единицы и филиалы.',
    'landing.steps.3.title': 'Команда вносит данные',
    'landing.steps.3.text': 'Приход, остатки и продажи — отчёты видны в реальном времени.',
    'landing.pricing.title': 'Тарифы',
    'landing.pricing.subtitle': '14 дней бесплатно, затем выберите тариф. Оплата через Payme.',
    'landing.price.period': '/мес',
    'landing.price.popular': 'Популярный',
    'landing.price.basic.f1': '1 кухня или филиал',
    'landing.price.basic.f2': 'До 10 сотрудников',
    'landing.price.basic.f3': 'Все типы операций и отчёты',
    'landing.price.basic.f4': 'Экспорт в Excel в любой момент',
    'landing.price.pro.f1': '10 кухонь или филиалов',
    'landing.price.pro.f2': 'До 50 сотрудников',
    'landing.price.pro.f3': 'Всё из Basic',
    'landing.price.pro.f4': 'Для сетей и растущих команд',
    'landing.testimonials.title': 'Что говорят владельцы',
    'landing.faq.title': 'Частые вопросы',
    'landing.faq.q1': 'Как быстро можно начать?',
    'landing.faq.a1': 'Регистрация занимает пару минут: создаёте аккаунт, добавляете продукты и кухни — команда вносит данные в тот же день.',
    'landing.faq.q2': 'Нужна ли карта для пробного периода?',
    'landing.faq.a2': 'Нет. Первые 14 дней бесплатны и без карты. После триала выбираете тариф и оплачиваете через Payme.',
    'landing.faq.q3': 'Кто видит мои данные?',
    'landing.faq.a3': 'Каждая организация работает со своими изолированными данными. Доступ есть только у ваших сотрудников по ролям.',
    'landing.faq.q4': 'Можно ли выгрузить данные?',
    'landing.faq.a4': 'Да, отчёты и историю операций можно выгрузить в Excel в любой момент.',

    // SaaS
    'saas.plan.basic': 'Базовый тариф',
    'saas.plan.pro': 'Про тариф',
    'saas.limit_reached': 'Лимит кухонь исчерпан',
    'saas.limit_desc': 'На Базовом тарифе доступна только 1 кухня.',
    'saas.upgrade_title': 'Обновитесь до Про',
    'saas.upgrade_desc': 'Получите безлимитное количество кухонь с тарифом Про.',
    'saas.upgrade_btn': 'Перейти на Про',
    'saas.current_usage': 'Использовано',
    'saas.unlimited': 'Безлимит',
    'saas.basic_features': 'Лимит: 1 кухня',
    'saas.pro_features': 'Безлимитные кухни',

    // Settings & Billing
    'set.title': 'Настройки',
    'set.tab.general': 'Общие',
    'set.tab.users': 'Сотрудники',
    'set.tab.billing': 'Тарифы и Оплата',
    'set.users.add': 'Добавить сотрудника',
    'set.users.role': 'Роль',
    'set.users.role.admin': 'Менеджер (Админ)',
    'set.users.role.kitchen': 'Повар (Кухня)',
    'set.users.fullname': 'ФИО',
    'set.users.username': 'Логин',
    'set.users.password': 'Пароль',
    'set.users.delete_confirm': 'Вы уверены, что хотите удалить сотрудника?',
    'set.users.limit': 'Лимит сотрудников исчерпан',
    'set.users.desc': 'Управляйте доступом сотрудников к вашей организации.',
    
    // Settings General
    'set.gen.profile': 'Профиль организации',
    'set.gen.org_name': 'Название организации',
    'set.gen.phone': 'Телефон',
    'set.gen.email': 'Email',
    'set.gen.address': 'Адрес',
    'set.gen.finance': 'Финансы и Регион',
    'set.gen.currency': 'Валюта',
    'set.gen.tax': 'Налог (%)',
    'set.gen.inventory': 'Правила инвентаризации',
    'set.gen.low_stock': 'Порог низкого запаса',
    'set.gen.save': 'Сохранить',
    'set.gen.saved': 'Настройки сохранены',

    // Billing
    'bill.free': 'Бесплатно',
    'bill.current': 'Текущий тариф',
    'bill.cycle': '/ мес',
    'bill.feature.kitchens': 'Кухни',
    'bill.feature.users': 'Пользователи',
    'bill.feature.dailyReports': 'Ежедневные отчёты для владельца',
    'bill.feature.analytics': 'Расширенная аналитика',
    'bill.feature.support': 'Приоритетная поддержка',
    'bill.btn.upgrade': 'Улучшить',
    'bill.btn.downgrade': 'Понизить',
    'bill.btn.current': 'Ваш тариф',
    'bill.btn.renew': 'Продлить',
    'bill.modal.title': 'Подтверждение смены тарифа',
    'bill.modal.desc': 'Вы собираетесь изменить тариф подписки.',
    'bill.modal.new_plan': 'Новый тариф',
    'bill.modal.price': 'Цена',
    'bill.modal.total': 'Итого к оплате',
    'bill.modal.confirm': 'Оплатить и перейти',
    'bill.modal.processing': 'Обработка...',
    'bill.pay_now': 'Оплатить',

    // Common
    'common.show': 'Показать',
    'common.entries': 'записей',
    'common.prev': 'Назад',
    'common.next': 'Вперед',
    'common.loading': 'Загрузка...',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',

    // QuickInput modal/edit
    'qi.edit_entry': 'Редактировать',
    'qi.time': 'Время',
    'qi.product_details': 'Детали продукта',
    'qi.unit_price': 'Цена за ед.',
    'qi.total_price': 'Итого',
    'qi.save_changes': 'Сохранить',
    'qi.confirm_delete': 'Подтвердить удаление',
    'qi.delete_op_msg': 'Вы уверены, что хотите удалить эту операцию? Это действие нельзя отменить.',

    // Settings billing
    'set.billing.desc': 'Управление подпиской и оплатой.',
    'set.billing.trial': 'Новым клиентам доступно 14 дней бесплатно.',
    'set.billing.history': 'История платежей',
    'set.billing.th_date': 'Дата',
    'set.billing.th_plan': 'Тариф',
    'set.billing.th_amount': 'Сумма',
    'set.billing.th_status': 'Статус',
    'set.billing.recommended': 'Рекомендуем',

    // Settings profile
    'set.profile.identity': 'Личные данные',
    'set.threshold_help': 'Порог выделит продукты красным в отчётах при низком остатке.',

    // Chart
    'dash.chart.daily': 'День',
    'dash.chart.cumulative': 'Накопительный',
    'dash.chart.sales': 'Продажи',
    'dash.chart.cost': 'Закупки',
    'dash.chart.cum_sales': 'Накоп. Продажи',
    'dash.chart.cum_cost': 'Накоп. закупки',
    'dash.chart.product': 'По продуктам',
    'dash.chart.prod_expense': 'Расход продукта (кол-во)',
    'dash.chart.margin': 'Разница за день',
    'dash.chart.prod_hint': 'Расход считается в дни, когда зафиксирован остаток.',

    // Products — category modal
    'prod.manage_cat': 'Управление категориями',
    'prod.new_cat_placeholder': 'Название новой категории...',

    // Kitchens — plan upsell
    'kit.pro_plan_includes': 'Тариф Pro включает:',
    'kit.feature.analytics': 'Расширенная аналитика (скоро)',
    'kit.feature.priority': 'Приоритетная поддержка',

    // Login — demo block
    'login.demo_creds': 'Демо данные',
    'login.client_admin': 'Клиент Администратор',
    'login.kitchen_staff': 'Сотрудник кухни',
    'login.access_limited': 'Доступ ограничен',
    // Subscription expiry banner
    'subscription.expiring_soon': 'Ваш план истекает {date}.',
    'subscription.expired': 'Ваш план истёк.',
    'subscription.renew_now': 'Продлить',
    // Admin panel
    'admin.suspend': 'Приостановить',
    'admin.unsuspend': 'Активировать',
    'admin.suspend_confirm': 'Приостановить организацию?',
    'admin.org_detail': 'Детали организации',
    'admin.audit_log': 'Аудит-лог',
    'admin.audit.all_events': 'Все события',
    'admin.audit.all_orgs': 'Все организации',
    'admin.plans_tab': 'Тарифы',
    'admin.m.tenants': 'Всего клиентов',
    'admin.m.mrr': 'MRR (UZS)',
    'admin.m.active': 'Активных',
    'admin.m.licensed': 'Лицензий',
    'admin.orgs': 'Организации',
    'admin.new_tenant': 'Новый клиент',
    'admin.search_tenants': 'Поиск клиентов...',
    'admin.act.users': 'Пользователи',
    'admin.act.edit': 'Редактировать',
    'admin.act.suspend': 'Приостановить',
    'admin.act.activate': 'Активировать',
    'admin.act.delete': 'Удалить',
    'prod.btn.categories': 'Категории',
    'admin.event_type': 'Тип события',
    'admin.actor': 'Инициатор',
    'admin.target': 'Объект',
    'admin.old_value': 'До',
    'admin.new_value': 'После',
    'admin.kitchens_tab': 'Кухни',
    'admin.products_tab': 'Продукты',
    'admin.users_tab': 'Пользователи',
    'admin.payments_tab': 'Платежи',
    'admin.edit_tab': 'Редактировать',
    'admin.org_suspended': 'Организация приостановлена',
    'access.suspended.title': 'Доступ ограничен',
    'access.suspended.text': 'Доступ временно ограничен. Выберите тариф, чтобы продолжить работу, или обратитесь к владельцу/администратору.',
    'access.suspended.pay_title': 'Продолжить с тарифом',
    'access.suspended.pay_error': 'Не удалось открыть оплату. Попробуйте позже.',
    'access.suspended.logout': 'Выйти',
  },
  uz: {
    // Navigation & Layout
    'nav.dashboard': 'Bosh sahifa',
    'nav.analytics': 'Tahlil',
    'nav.quick_input': 'Ma\'lumot kiritish',
    'nav.kitchens': 'Oshxonalar',
    'nav.products': 'Mahsulotlar',
    'nav.reports': 'Hisobotlar',
    'nav.settings': 'Sozlamalar',
    'nav.logout': 'Chiqish',
    'nav.main_menu': 'Asosiy menyu',
    'nav.explore': 'Boshqalar',
    'header.greeting': 'Xayrli kun, Shef',
    'header.role': 'Bosh oshpaz',

    // Dashboard
    'dash.total_revenue': 'Jami tushum',
    'dash.revenue_period': 'Davr tushumi',
    'dash.incoming_vol': 'Kirim hajmi',
    'dash.units_received': 'Qabul qilingan birliklar',
    'dash.sales_count': 'Sotuvlar soni',
    'plan.upgrade_cta': "Pro'ga o'tish",
    'plan.history_limit': "Basic tarifi oxirgi 30 kunlik tarixni ko'rsatadi. Pro'da cheklov yo'q.",
    'plan.pro_feature.title': 'Pro tarifida mavjud',
    'plan.pro_feature.product_chart': "Mahsulotlar bo'yicha tahlil grafigi Pro tarifida ochiladi.",
    'plan.upsell.later': 'Keyinroq',
    'plan.limit_near': 'Oshxona limiti deyarli tugadi',
    'plan.limit_reached': 'Oshxona limitiga yetildi',
    'plan.limit_near_users': 'Xodimlar limiti deyarli tugadi',
    'plan.limit_reached_users': 'Xodimlar limitiga yetildi',
    'dash.no_data': 'Bu davr uchun ma\'lumot yo\'q',
    'dash.no_data.hint': 'Boshqa sana oralig\'ini tanlang yoki "Ma\'lumot kiritish"da amallar qo\'shing.',
    'dash.transactions': 'Tranzaksiyalar',
    'dash.operations': 'Operatsiyalar',
    'dash.total_events': 'Jami yozuvlar',
    'dash.trends': 'Tranzaksiya tendentsiyalari',
    'dash.profit_summary': 'Foyda hisoboti',
    'dash.see_details': 'Batafsil',
    'dash.yearly_profit': 'Yillik loyiha foydasi',
    'dash.weekly_profit': 'Haftalik loyiha foydasi',
    'dash.filter.daily': 'Kunlik',
    'dash.filter.monthly': 'Oylik',
    'dash.filter.all_kitchens': 'Barcha oshxonalar',
    'dash.avg_yearly': 'O\'rtacha yillik',
    'dash.avg_monthly': 'O\'rtacha oylik',
    'dash.from': 'Dan',
    'dash.main_table': 'Asosiy jadval',
    'dash.sales_cost_dynamics': 'Sotuv va xaridlar',

    // Quick Input
    'qi.title': 'Ma\'lumot kiritish',
    'qi.op.incoming': 'Kirim',
    'qi.op.daily': 'Qoldiq',
    'qi.op.transfer': 'O\'tkazma',
    'qi.op.sale': 'Sotish',
    'qi.date': 'Sana',
    'qi.kitchen': 'Oshxona',
    'qi.from_kitchen': 'Oshxonadan',
    'qi.to_kitchen': 'Oshxonaga',
    'qi.product': 'Mahsulot',
    'qi.product_ph': 'Kod yoki nomni skanerlang...',
    'qi.qty': 'Miqdor',
    'qi.balance': 'Balans',
    'qi.price': 'Birlik narxi',
    'qi.revenue': 'Tushum (Birlik)',
    'qi.total_calc': 'Jami',
    'qi.save': 'Saqlash',
    'qi.history': 'Yaqinda kiritilganlar',
    'qi.search_ph': 'Mahsulotni qidirish...',
    'qi.all_types': 'Barcha turlar',
    'qi.all_kitchens': 'Barcha oshxonalar',
    'qi.not_found': 'Topilmadi',
    'qi.no_history': 'Filtrlar bo\'yicha tarix topilmadi.',
    'qi.unit': 'Birlik',
    'qi.total_count': 'Jami yozuvlar',
    'qi.total_amount': 'Jami summa',

    // Kitchens
    'kit.add': 'Oshxona qo\'shish',
    'kit.search_ph': 'Oshxona qidirish...',
    'kit.name': 'Oshxona nomi',
    'kit.status': 'Holat',
    'kit.actions': 'Amallar',
    'kit.active': 'Faol',
    'kit.inactive': 'Faol emas',
    'kit.no_data': 'Mezonlarga mos oshxonalar topilmadi.',
    'kit.modal.edit': 'Oshxonani tahrirlash',
    'kit.modal.add': 'Yangi oshxona qo\'shish',
    'kit.modal.status_label': 'Ishlash holati',
    'kit.modal.status_desc': 'Ushbu oshxona joylashuvini yoqish yoki o\'chirish',
    'kit.create': 'Oshxona yaratish',
    'kit.update': 'Oshxonani yangilash',
    'kit.delete_confirm': 'Ushbu oshxonani o\'chirishni xohlaysizmi?',

    // Products
    'prod.add': 'Mahsulot qo\'shish',
    'prod.search_ph': 'Mahsulot nomi yoki kodi bo\'yicha qidirish...',
    'prod.code': 'Kod',
    'prod.name': 'Mahsulot nomi',
    'prod.category': 'Toifa',
    'prod.unit': 'Birlik',
    'prod.no_data': 'Mahsulotlar topilmadi.',
    'prod.modal.edit': 'Mahsulotni tahrirlash',
    'prod.modal.add': 'Yangi mahsulot qo\'shish',
    'prod.create': 'Mahsulot yaratish',
    'prod.update': 'Mahsulotni yangilash',
    'prod.delete_title': 'Mahsulotni o\'chirish',
    'prod.delete_confirm': 'Ushbu mahsulotni o\'chirasizmi? Operatsiyalar tarixi saqlanib qoladi.',
    'prod.cat.all': 'Barchasi',

    // Analytics
    'anl.kitchen_branch': 'Oshxona / Filial',
    'anl.apply': 'Filtrlarni qo\'llash',
    'anl.export': 'Excelga eksport',
    'anl.dept_analytics': 'Bo\'lim tahlili',
    'anl.sales_dynamics': 'Sotuv dinamikasi',
    'anl.col.dept': 'Bo\'lim',
    'anl.col.start': 'Bosh qoldiq',
    'anl.col.in': 'Kirim',
    'anl.col.exp': 'Chiqim',
    'anl.col.end': 'Oxir qoldiq',
    'anl.col.sales': 'Sotuv(sum)',
    'anl.col.mrk': 'Marja(sum)',
    'anl.col.trns': 'O\'tk',
    'anl.col.trns_in': 'O\'tk(Kir)',
    'anl.col.trns_out': 'O\'tk(Chiq)',
    'anl.col.dept.full': 'Bo\'lim',
    'anl.col.start.full': 'Bosh qoldiq',
    'anl.col.in.full': 'Kirim',
    'anl.col.exp.full': 'Chiqim',
    'anl.col.end.full': 'Oxirgi qoldiq',
    'anl.col.sales.full': 'Sotuv summasi',
    'anl.col.mrk.full': 'Marja',
    'anl.col.trns.full': 'O\'tkazma',
    'anl.col.trns_in.full': 'O\'tkazma (Kirim)',
    'anl.col.trns_out.full': 'O\'tkazma (Chiqim)',
    'anl.total': 'JAMI',
    'anl.date_from': 'Sana dan',
    'anl.date_to': 'Sana gacha',

    // Reports
    'rep.title': 'Inventar balansi hisoboti',
    'rep.col.code': 'Kod',
    'rep.col.product': 'Mahsulot nomi',
    'rep.col.incoming': 'Kirim',
    'rep.col.sales': 'Sotuv',
    'rep.col.transfer': 'O\'tkazma (Netto)',
    'rep.col.balance': 'Joriy balans',
    'rep.no_data': 'Ushbu davr uchun ma\'lumot topilmadi.',
    'rep.qty': 'Miqd',
    'rep.sum': 'Sum',

    // Login
    'auth.welcome': 'Xush kelibsiz',
    'auth.subtitle': 'MARGA MANAGER',
    'auth.username': 'Foydalanuvchi nomi',
    'auth.password': 'Parol',
    'auth.signin': 'Kirish',
    'auth.error': 'Login yoki parol noto\'g\'ri.',
    'auth.creds': 'Standart hisob ma\'lumotlari:',
    'register.title': '14 kun bepul boshlang',
    'register.subtitle': 'Tashkilotni yarating va kabinetga kiring.',
    'register.organization': 'Tashkilot nomi',
    'register.owner': 'Ismingiz',
    'register.phone': 'Telefon raqami',
    'register.submit': 'Akkaunt yaratish',
    'register.error': 'Ro\'yxatdan o\'tib bo\'lmadi. Maydonlarni tekshirib qayta urinib ko\'ring.',
    'register.have_account': 'Kirish mavjudmi?',
    'register.no_account': 'Hali akkaunt yo\'qmi?',
    'onboarding.title': 'Birinchi filialni qo\'shing',
    'onboarding.subtitle': 'Qoldiq, sotuv va kunlik ishni kiritishni boshlash uchun shu yetarli.',
    'onboarding.branch': 'Filial yoki sex nomi',
    'onboarding.branch_default': 'Asosiy filial',
    'onboarding.submit': 'Ishni boshlash',
    'onboarding.error': 'Filialni yaratib bo\'lmadi.',

    // Landing
    'landing.login': 'Kirish',
    'landing.badge': 'Kafe, sex va filial egalari uchun',
    'landing.hero.title': 'Xodimlarni va ombordagi qoldiqlarni oson boshqaring',
    'landing.hero.subtitle': 'MARGA MANAGER ombor hisobini tartibga soladi va biznes egasi bilan xodimlar o\'rtasidagi ish qoidalarini aniq qiladi.',
    'landing.hero.audience': 'Kafe, qandolat sexlari va kichik ishlab chiqarishlar uchun. Jamoa ishi va mahsulot harakatini tez ko\'rish oson bo\'ladi.',
    'landing.cta.open': '14 kun bepul boshlash',
    'landing.cta.inside': 'Qanday ishlaydi',
    'landing.snapshot.title': 'Ega nimani ko\'radi',
    'landing.snapshot.subtitle': 'Kunlik ishning asosiy ko\'rinishi',
    'landing.snapshot.status': 'Hozir',
    'landing.metric.margin': 'Kunlik marja',
    'landing.metric.margin.value': '4.2 mln',
    'landing.metric.sales': 'Sotuv va tannarx',
    'landing.metric.sales.value': '+18%',
    'landing.metric.stock': 'Xom ashyo',
    'landing.metric.stock.value': '126 kg',
    'landing.row.margin': 'Har kunlik yalpi daromad (marja)',
    'landing.row.margin.value': '1 240 000',
    'landing.row.dynamics': 'Sotuv va tannarx dinamikasi',
    'landing.row.dynamics.value': '+18%',
    'landing.row.stock': 'Har kunlik xom ashyo qoldig\'i',
    'landing.row.stock.value': '126 kg',
    'landing.row.expense': 'Har kunlik xom ashyo xarajati',
    'landing.row.expense.value': '870 000',
    'landing.row.departments': 'Bo\'limlarning kunlik natijalari',
    'landing.row.departments.value': '3 bo\'lim',
    'landing.module.input.title': 'Tez ma\'lumot kiritish',
    'landing.module.input.text': 'Xodim kirim, qoldiq, o\'tkazma va sotuvni tez kiritadi. Biznes egasi hammasini tushunarli ko\'rinishda ko\'radi.',
    'landing.quick.incoming': 'Kirim',
    'landing.quick.incoming.text': 'Yangi mahsulotni tez kiriting.',
    'landing.quick.stock': 'Qoldiq',
    'landing.quick.stock.text': 'Nima qolganini ko\'ring.',
    'landing.quick.sales': 'Sotuv',
    'landing.quick.sales.text': 'Kunlik sotuvni yozib boring.',
    'landing.price.basic': 'Basic reja',
    'landing.price.basic.note': 'Oddiy kunlik nazorat uchun',
    'landing.price.pro': 'Pro reja',
    'landing.price.pro.note': 'Jamoa va filiallar uchun',
    'landing.price.trial': '14 kun bepul',
    'landing.module.rules.title': 'Ishda tartib',
    'landing.module.rules.text': 'Har bir xodimda o\'z kirishi bor. Kim nima qilganini va kim nima uchun javob berishini tushunish oson.',
    'landing.module.branches.title': 'Filiallar va mahsulotlar',
    'landing.module.branches.text': 'Mahsulotlar, qoldiqlar, oshxonalar, sexlar va filiallarni bitta joyda kuzatish mumkin.',
    'landing.module.saas.title': 'To\'lov va kirish',
    'landing.module.saas.text': 'Tariflar, foydalanuvchilar, to\'lov va kirish muddatini qo\'lda adashmasdan boshqarish mumkin.',
    'landing.saas.title': 'Turli mijozlar uchun tayyor',
    'landing.saas.text': 'Har bir mijoz o\'z ma\'lumotlari, xodimlari, filiallari va to\'lovlari bilan alohida ishlaydi.',
    'landing.saas.item.tenancy': 'Mijoz ma\'lumotlari ajratilgan',
    'landing.saas.item.auth': 'Login va parol bilan kirish',
    'landing.saas.item.limits': 'Tarif bo\'yicha cheklovlar',
    'landing.saas.item.audit': 'To\'lov va o\'zgarishlar tarixi',
    'landing.roles.title': 'Har kim faqat o\'ziga keraklisini ko\'radi',
    'landing.role.super.title': 'Servis egasi',
    'landing.role.super': 'mijozlar, tariflar va asosiy sozlamalarni boshqaradi',
    'landing.role.admin.title': 'Biznes boshqaruvchisi',
    'landing.role.admin': 'filiallar, mahsulotlar, xodimlar, hisobotlar va to\'lovni boshqaradi',
    'landing.role.kitchen.title': 'Xodim',
    'landing.role.kitchen': 'ortiqcha sozlamalarsiz kunlik ma\'lumotlarni tez kiritadi',
    'landing.footer.title': 'Oddiy nazoratdan boshlang',
    'landing.footer.text': 'Kabinetni oching va ombor, xodimlar va kunlik ish qanday tartibda turishini ko\'ring.',
    'landing.footer.roles': '3 kirish darajasi',
    'landing.footer.devices': 'Kompyuter + telefon',
    'landing.nav.features': 'Imkoniyatlar',
    'landing.nav.pricing': 'Tariflar',
    'landing.cta.note': 'Bank kartasi shart emas — istalgan payt bekor qilish mumkin',
    'landing.pain.title': 'Tanish muammolarmi?',
    'landing.pain.before.label': 'Hozir — daftarda',
    'landing.pain.after.label': 'Marga Managerda',
    'landing.pain.1.before': 'Hisob daftar va chatlarda yuritiladi',
    'landing.pain.1.after': 'Barcha amallar tarixi bilan bitta tizimda',
    'landing.pain.2.before': 'Qoldiqlar haftada bir marta qo\'lda sanaladi',
    'landing.pain.2.after': 'Har bir oshxona uchun kunlik qoldiq va xarajat',
    'landing.pain.3.before': 'Marja qayerga ketayotgani noaniq',
    'landing.pain.3.after': 'Ustama va tannarx avtomatik hisoblanadi',
    'landing.steps.title': 'Bu qanday ishlaydi',
    'landing.steps.1.title': 'Ro\'yxatdan o\'ting',
    'landing.steps.1.text': 'Bir necha daqiqada akkaunt va tashkilot yarating.',
    'landing.steps.2.title': 'Mahsulot va oshxonalarni qo\'shing',
    'landing.steps.2.text': 'Katalog, o\'lchov birliklari va filiallarni bir marta to\'ldiring.',
    'landing.steps.3.title': 'Jamoa kunlik ma\'lumot kiritadi',
    'landing.steps.3.text': 'Kirim, qoldiq va sotuvlar — hisobotlar real vaqtda ko\'rinadi.',
    'landing.pricing.title': 'Tariflar',
    'landing.pricing.subtitle': '14 kun bepul, so\'ng tarifni tanlang. To\'lov Payme orqali.',
    'landing.price.period': '/oy',
    'landing.price.popular': 'Ommabop',
    'landing.price.basic.f1': '1 ta oshxona yoki filial',
    'landing.price.basic.f2': '10 tagacha xodim',
    'landing.price.basic.f3': 'Barcha amal turlari va hisobotlar',
    'landing.price.basic.f4': 'Istalgan payt Excelga eksport',
    'landing.price.pro.f1': '10 ta oshxona yoki filial',
    'landing.price.pro.f2': '50 tagacha xodim',
    'landing.price.pro.f3': 'Basic tarifidagi hammasi',
    'landing.price.pro.f4': 'Tarmoqlar va o\'sayotgan jamoalar uchun',
    'landing.testimonials.title': 'Egalari nima deydi',
    'landing.faq.title': 'Ko\'p so\'raladigan savollar',
    'landing.faq.q1': 'Qancha tez boshlash mumkin?',
    'landing.faq.a1': 'Ro\'yxatdan o\'tish bir necha daqiqa: akkaunt yarating, mahsulot va oshxonalarni qo\'shing — jamoa o\'sha kuniyoq ma\'lumot kiritadi.',
    'landing.faq.q2': 'Sinov davri uchun karta kerakmi?',
    'landing.faq.a2': 'Yo\'q. Dastlabki 14 kun kartasiz bepul. Sinovdan so\'ng tarifni tanlab, Payme orqali to\'laysiz.',
    'landing.faq.q3': 'Ma\'lumotlarimni kim ko\'radi?',
    'landing.faq.a3': 'Har bir tashkilot o\'z ma\'lumotlari bilan alohida ishlaydi. Kirish faqat xodimlaringizga rollar bo\'yicha beriladi.',
    'landing.faq.q4': 'Ma\'lumotlarni yuklab olsam bo\'ladimi?',
    'landing.faq.a4': 'Ha, hisobotlar va amallar tarixini istalgan payt Excelga yuklab olish mumkin.',

    // SaaS
    'saas.plan.basic': 'Basic rejasi',
    'saas.plan.pro': 'Pro rejasi',
    'saas.limit_reached': 'Oshxona chekloviga yetdi',
    'saas.limit_desc': 'Basic rejasida 1 ta oshxona limiti mavjud.',
    'saas.upgrade_title': 'Pro ga o\'tish',
    'saas.upgrade_desc': 'Pro rejasi bilan cheksiz oshxonalar va kengaytirilgan xususiyatlarga ega bo\'ling.',
    'saas.upgrade_btn': 'Pro ga o\'tish',
    'saas.current_usage': 'Foydalanish',
    'saas.unlimited': 'Cheksiz',
    'saas.basic_features': '1 ta oshxona limiti',
    'saas.pro_features': 'Cheksiz oshxonalar',

    // Settings & Billing
    'set.title': 'Sozlamalar',
    'set.tab.general': 'Umumiy',
    'set.tab.users': 'Jamoa a\'zolari',
    'set.tab.billing': 'Rejalar va to\'lov',
    'set.users.add': 'A\'zo qo\'shish',
    'set.users.role': 'Rol',
    'set.users.role.admin': 'Menejer (Admin)',
    'set.users.role.kitchen': 'Oshxona xodimi',
    'set.users.fullname': 'To\'liq ism',
    'set.users.username': 'Foydalanuvchi nomi',
    'set.users.password': 'Parol',
    'set.users.delete_confirm': 'Ushbu foydalanuvchini o\'chirishni xohlaysizmi?',
    'set.users.limit': 'Foydalanuvchi limiti yetdi',
    'set.users.desc': 'Tashkilotingiz ish joyiga kim kirishini boshqaring.',
    
    // Settings General
    'set.gen.profile': 'Tashkilot profili',
    'set.gen.org_name': 'Tashkilot nomi',
    'set.gen.phone': 'Telefon raqami',
    'set.gen.email': 'Email manzili',
    'set.gen.address': 'Manzil',
    'set.gen.finance': 'Moliya va Hudud',
    'set.gen.currency': 'Valyuta',
    'set.gen.tax': 'Soliq (%)',
    'set.gen.inventory': 'Ombor qoidalari',
    'set.gen.low_stock': 'Kam qoldiq chegarasi',
    'set.gen.save': 'Saqlash',
    'set.gen.saved': 'Sozlamalar saqlandi',

    // Billing
    'bill.free': 'Bepul',
    'bill.current': 'Joriy tarif',
    'bill.cycle': '/ oy',
    'bill.feature.kitchens': 'Oshxonalar',
    'bill.feature.users': 'Foydalanuvchilar',
    'bill.feature.dailyReports': 'Ega uchun kunlik hisobotlar',
    'bill.feature.analytics': 'Kengaytirilgan tahlil',
    'bill.feature.support': 'Tezkor yordam',
    'bill.btn.upgrade': 'Kuchaytirish',
    'bill.btn.downgrade': 'Pasaytirish',
    'bill.btn.current': 'Sizning tarifingiz',
    'bill.btn.renew': 'Uzaytirish',
    'bill.modal.title': 'Tarifni o\'zgartirishni tasdiqlash',
    'bill.modal.desc': 'Siz obuna tarifingizni o\'zgartirmoqchisiz.',
    'bill.modal.new_plan': 'Yangi tarif',
    'bill.modal.price': 'Narx',
    'bill.modal.total': 'Bugungi to\'lov',
    'bill.modal.confirm': 'To\'lash va o\'tish',
    'bill.modal.processing': 'Qayta ishlanmoqda...',
    'bill.pay_now': 'To\'lov qilish',

    // Common
    'common.show': 'Ko\'rsatish',
    'common.entries': 'yozuvlar',
    'common.prev': 'Oldingi',
    'common.next': 'Keyingi',
    'common.loading': 'Yuklanmoqda...',
    'common.cancel': 'Bekor qilish',
    'common.save': 'Saqlash',
    'common.edit': 'Tahrirlash',
    'common.delete': 'O\'chirish',

    // QuickInput modal/edit
    'qi.edit_entry': 'Tahrirlash',
    'qi.time': 'Vaqt',
    'qi.product_details': 'Mahsulot tafsilotlari',
    'qi.unit_price': 'Birlik narxi',
    'qi.total_price': 'Jami narx',
    'qi.save_changes': 'Saqlash',
    'qi.confirm_delete': 'O\'chirishni tasdiqlash',
    'qi.delete_op_msg': 'Bu amalni o\'chirishga ishonchingiz komilmi? Bu amalni bekor qilib bo\'lmaydi.',

    // Settings billing
    'set.billing.desc': 'Obuna va to\'lovni boshqarish.',
    'set.billing.trial': 'Yangi mijozlar uchun 14 kun bepul.',
    'set.billing.history': 'To\'lov tarixi',
    'set.billing.th_date': 'Sana',
    'set.billing.th_plan': 'Tarif',
    'set.billing.th_amount': 'Summa',
    'set.billing.th_status': 'Holat',
    'set.billing.recommended': 'Tavsiya',

    // Settings profile
    'set.profile.identity': 'Shaxsiy ma\'lumotlar',
    'set.threshold_help': 'Bu chegara hisobotlarda kam qoldiqli mahsulotlarni qizil rang bilan belgilaydi.',

    // Chart
    'dash.chart.daily': 'Kunlik',
    'dash.chart.cumulative': 'Yig\'indili',
    'dash.chart.sales': 'Sotuv',
    'dash.chart.cost': 'Xaridlar',
    'dash.chart.cum_sales': 'Jami Sotuv',
    'dash.chart.cum_cost': 'Jami xaridlar',
    'dash.chart.product': 'Mahsulotlar bo\'yicha',
    'dash.chart.prod_expense': 'Mahsulot sarfi (miqdor)',
    'dash.chart.margin': 'Kunlik farq',
    'dash.chart.prod_hint': "Sarf qoldiq qayd etilgan kunlarda hisoblanadi.",

    // Products — category modal
    'prod.manage_cat': 'Kategoriyalarni boshqarish',
    'prod.new_cat_placeholder': 'Yangi kategoriya nomi...',

    // Kitchens — plan upsell
    'kit.pro_plan_includes': 'Pro tarifiga kiradi:',
    'kit.feature.analytics': 'Kengaytirilgan tahlil (tez orada)',
    'kit.feature.priority': 'Ustuvor qo\'llab-quvvatlash',

    // Login — demo block
    'login.demo_creds': 'Demo ma\'lumotlar',
    'login.client_admin': 'Mijoz Admin',
    'login.kitchen_staff': 'Oshxona xodimi',
    'login.access_limited': 'Kirish cheklangan',
    // Subscription expiry banner
    'subscription.expiring_soon': 'Obunangiz {date} tugaydi.',
    'subscription.expired': 'Obunangiz tugagan.',
    'subscription.renew_now': 'Yangilash',
    // Admin panel
    'admin.suspend': 'To\'xtatish',
    'admin.unsuspend': 'Faollashtirish',
    'admin.suspend_confirm': 'Tashkilotni to\'xtatish?',
    'admin.org_detail': 'Tashkilot tafsilotlari',
    'admin.audit_log': 'Audit jurnali',
    'admin.audit.all_events': 'Barcha hodisalar',
    'admin.audit.all_orgs': 'Barcha tashkilotlar',
    'admin.plans_tab': 'Tariflar',
    'admin.m.tenants': 'Jami mijozlar',
    'admin.m.mrr': 'MRR (UZS)',
    'admin.m.active': 'Faol',
    'admin.m.licensed': 'Litsenziyalar',
    'admin.orgs': 'Tashkilotlar',
    'admin.new_tenant': 'Yangi mijoz',
    'admin.search_tenants': 'Mijoz qidirish...',
    'admin.act.users': 'Foydalanuvchilar',
    'admin.act.edit': 'Tahrirlash',
    'admin.act.suspend': "To'xtatish",
    'admin.act.activate': 'Faollashtirish',
    'admin.act.delete': "O'chirish",
    'prod.btn.categories': 'Kategoriyalar',
    'admin.event_type': 'Voqea turi',
    'admin.actor': 'Muallif',
    'admin.target': 'Ob\'ekt',
    'admin.old_value': 'Oldin',
    'admin.new_value': 'Keyin',
    'admin.kitchens_tab': 'Oshxonalar',
    'admin.products_tab': 'Mahsulotlar',
    'admin.users_tab': 'Foydalanuvchilar',
    'admin.payments_tab': 'To\'lovlar',
    'admin.edit_tab': 'Tahrirlash',
    'admin.org_suspended': 'Tashkilot to\'xtatilgan',
    'access.suspended.title': 'Kirish cheklangan',
    'access.suspended.text': 'Kirish vaqtincha cheklangan. Ishni davom ettirish uchun tarif tanlang yoki egasi/administrator bilan bog\'laning.',
    'access.suspended.pay_title': 'Tarif bilan davom etish',
    'access.suspended.pay_error': 'To\'lovni ochib bo\'lmadi. Keyinroq qayta urinib ko\'ring.',
    'access.suspended.logout': 'Chiqish',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('km_lang') as Language) || 'uz';
  });

  useEffect(() => {
    localStorage.setItem('km_lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
