
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Layout
    'nav.dashboard': 'Main Page',
    'nav.analytics': 'Analytics',
    'nav.quick_input': 'Data Entry',
    'nav.kitchens': 'Kitchens',
    'nav.products': 'Products',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.logout': 'Log out',
    'nav.main_menu': 'Main Menu',
    'nav.explore': 'Explore',
    'header.greeting': 'Good Afternoon, Chef',
    'header.role': 'Head Chef',
    
    // Dashboard
    'dash.total_revenue': 'Total Sales Revenue',
    'dash.revenue_period': 'Revenue in period',
    'dash.incoming_vol': 'Incoming Volume',
    'dash.units_received': 'Units received',
    'dash.sales_count': 'Sales Count',
    'dash.transactions': 'Transactions',
    'dash.operations': 'Operations',
    'dash.total_events': 'Total logged events',
    'dash.trends': 'Transaction Trends',
    'dash.profit_summary': 'Profit Summary',
    'dash.see_details': 'See Details',
    'dash.yearly_profit': 'Yearly Project Profit',
    'dash.weekly_profit': 'Weekly Project Profit',
    'dash.filter.daily': 'Daily',
    'dash.filter.monthly': 'Monthly',
    'dash.filter.all_kitchens': 'All Kitchens',
    'dash.avg_yearly': 'Avg yearly',
    'dash.avg_monthly': 'Avg monthly',
    'dash.from': 'From',
    'dash.main_table': 'Main Table',
    'dash.sales_cost_dynamics': 'Sales and Cost Dynamics',

    // Quick Input
    'qi.title': 'Data Entry',
    'qi.op.incoming': 'Incoming',
    'qi.op.daily': 'Stock',
    'qi.op.transfer': 'Transfer',
    'qi.op.sale': 'Sale',
    'qi.date': 'Date',
    'qi.kitchen': 'Kitchen',
    'qi.from_kitchen': 'From Kitchen',
    'qi.to_kitchen': 'To Kitchen',
    'qi.product': 'Product',
    'qi.product_ph': 'Scan code or type name...',
    'qi.qty': 'Quantity',
    'qi.balance': 'Balance',
    'qi.price': 'Unit Price',
    'qi.revenue': 'Revenue (Unit)',
    'qi.total_calc': 'Total',
    'qi.save': 'Save',
    'qi.history': 'Recent History',
    'qi.search_ph': 'Search product...',
    'qi.all_types': 'All Types',
    'qi.all_kitchens': 'All Kitchens',
    'qi.not_found': 'Not found',
    'qi.no_history': 'No history found matching filters.',
    'qi.unit': 'Unit',
    'qi.total_count': 'Total Entries',
    'qi.total_amount': 'Total Sum',

    // Kitchens
    'kit.add': 'Add Kitchen',
    'kit.search_ph': 'Search kitchen...',
    'kit.name': 'Kitchen Name',
    'kit.status': 'Status',
    'kit.actions': 'Actions',
    'kit.active': 'Active',
    'kit.inactive': 'Inactive',
    'kit.no_data': 'No kitchens found matching your criteria.',
    'kit.modal.edit': 'Edit Kitchen',
    'kit.modal.add': 'Add New Kitchen',
    'kit.modal.status_label': 'Operational Status',
    'kit.modal.status_desc': 'Enable or disable this kitchen location',
    'kit.create': 'Create Kitchen',
    'kit.update': 'Update Kitchen',
    'kit.delete_confirm': 'Are you sure you want to delete this kitchen?',

    // Products
    'prod.add': 'Add Product',
    'prod.search_ph': 'Search product name or code...',
    'prod.code': 'Code',
    'prod.name': 'Product Name',
    'prod.category': 'Category',
    'prod.unit': 'Unit',
    'prod.no_data': 'No products found.',
    'prod.modal.edit': 'Edit Product',
    'prod.modal.add': 'Add New Product',
    'prod.create': 'Create Product',
    'prod.update': 'Update Product',
    'prod.delete_title': 'Delete Product',
    'prod.delete_confirm': 'Delete this product? Operations history will remain.',
    'prod.cat.all': 'All',

    // Analytics
    'anl.kitchen_branch': 'Kitchen / Branch',
    'anl.apply': 'Apply Filters',
    'anl.export': 'Export Excel',
    'anl.dept_analytics': 'Department Analytics',
    'anl.sales_dynamics': 'Sales Dynamics',
    'anl.col.dept': 'Dept',
    'anl.col.start': 'Start',
    'anl.col.in': 'In',
    'anl.col.exp': 'Exp',
    'anl.col.end': 'End',
    'anl.col.sales': 'Sales(sum)',
    'anl.col.mrk': 'Mrk(sum)',
    'anl.col.trns': 'Trns',
    'anl.col.trns_in': 'Trns(In)',
    'anl.col.trns_out': 'Trns(Out)',
    'anl.total': 'TOTAL',
    'anl.date_from': 'Date From',
    'anl.date_to': 'Date To',

    // Reports
    'rep.title': 'Inventory Balance Report',
    'rep.col.code': 'Code',
    'rep.col.product': 'Product Name',
    'rep.col.incoming': 'Incoming',
    'rep.col.sales': 'Sales',
    'rep.col.transfer': 'Transfer (Net)',
    'rep.col.balance': 'Current Balance',
    'rep.no_data': 'No data found for this period.',
    'rep.qty': 'Qty',
    'rep.sum': 'Sum',

    // Login
    'auth.welcome': 'Welcome Back',
    'auth.subtitle': 'MARGA MENEGER',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.signin': 'Sign In',
    'auth.error': 'Invalid credentials. Try admin / admin123',
    'auth.creds': 'Default credentials:',

    // SaaS
    'saas.plan.basic': 'Basic Plan',
    'saas.plan.pro': 'Pro Plan',
    'saas.limit_reached': 'Kitchen Limit Reached',
    'saas.limit_desc': 'You have reached the limit of 1 kitchen on the Basic plan.',
    'saas.upgrade_title': 'Upgrade to Pro',
    'saas.upgrade_desc': 'Get unlimited kitchens and advanced features with the Pro plan.',
    'saas.upgrade_btn': 'Upgrade to Pro',
    'saas.current_usage': 'Usage',
    'saas.unlimited': 'Unlimited',
    'saas.basic_features': '1 Kitchen limit',
    'saas.pro_features': 'Unlimited Kitchens',

    // Settings & Billing
    'set.title': 'Settings',
    'set.tab.general': 'General',
    'set.tab.users': 'Team Members',
    'set.tab.billing': 'Plans & Billing',
    'set.users.add': 'Add Member',
    'set.users.role': 'Role',
    'set.users.role.admin': 'Manager (Admin)',
    'set.users.role.kitchen': 'Kitchen Staff',
    'set.users.fullname': 'Full Name',
    'set.users.username': 'Username',
    'set.users.password': 'Password',
    'set.users.delete_confirm': 'Are you sure you want to remove this user?',
    'set.users.limit': 'User limit reached',
    'set.users.desc': 'Manage who has access to your organization workspace.',
    
    // Settings General
    'set.gen.profile': 'Organization Profile',
    'set.gen.org_name': 'Restaurant Name',
    'set.gen.phone': 'Phone Number',
    'set.gen.email': 'Email Address',
    'set.gen.address': 'Physical Address',
    'set.gen.finance': 'Finance & Region',
    'set.gen.currency': 'Currency',
    'set.gen.tax': 'Tax Rate (%)',
    'set.gen.inventory': 'Inventory Rules',
    'set.gen.low_stock': 'Low Stock Threshold',
    'set.gen.save': 'Save Changes',
    'set.gen.saved': 'Settings saved successfully',

    // Billing
    'bill.current': 'Current Plan',
    'bill.cycle': '/ month',
    'bill.feature.kitchens': 'Kitchens',
    'bill.feature.users': 'Users',
    'bill.feature.analytics': 'Advanced Analytics',
    'bill.feature.support': 'Priority Support',
    'bill.btn.upgrade': 'Upgrade',
    'bill.btn.downgrade': 'Downgrade',
    'bill.btn.current': 'Current Plan',
    'bill.modal.title': 'Confirm Subscription Change',
    'bill.modal.desc': 'You are about to switch your subscription plan.',
    'bill.modal.new_plan': 'New Plan',
    'bill.modal.price': 'Price',
    'bill.modal.total': 'Total due today',
    'bill.modal.confirm': 'Confirm & Pay',
    'bill.modal.processing': 'Processing...',
    
    // Common
    'common.show': 'Show',
    'common.entries': 'entries',
    'common.prev': 'Previous',
    'common.next': 'Next',

    // Chart
    'dash.chart.daily': 'Daily',
    'dash.chart.cumulative': 'Cumulative',
    'dash.chart.sales': 'Sales',
    'dash.chart.cost': 'Cost',
    'dash.chart.cum_sales': 'Cumulative Sales',
    'dash.chart.cum_cost': 'Cumulative Cost',
    'dash.chart.product': 'By Product',
    'dash.chart.prod_expense': 'Product Expense',
  },
  ru: {
    // Navigation & Layout
    'nav.dashboard': 'Главная',
    'nav.analytics': 'Аналитика',
    'nav.quick_input': 'Ввод данных',
    'nav.kitchens': 'Кухни',
    'nav.products': 'Продукты',
    'nav.reports': 'Отчеты',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
    'nav.main_menu': 'Главное меню',
    'nav.explore': 'Разное',
    'header.greeting': 'Добрый день, Шеф',
    'header.role': 'Шеф-повар',

    // Dashboard
    'dash.total_revenue': 'Общая выручка',
    'dash.revenue_period': 'Выручка за период',
    'dash.incoming_vol': 'Объем прихода',
    'dash.units_received': 'Единиц получено',
    'dash.sales_count': 'Кол-во продаж',
    'dash.transactions': 'Транзакции',
    'dash.operations': 'Операции',
    'dash.total_events': 'Всего записей',
    'dash.trends': 'Тренд транзакций',
    'dash.profit_summary': 'Сводка по прибыли',
    'dash.see_details': 'Подробнее',
    'dash.yearly_profit': 'Годовая прибыль',
    'dash.weekly_profit': 'Недельная прибыль',
    'dash.filter.daily': 'День',
    'dash.filter.monthly': 'Месяц',
    'dash.filter.all_kitchens': 'Все кухни',
    'dash.avg_yearly': 'Сред. год',
    'dash.avg_monthly': 'Сред. месяц',
    'dash.from': 'С',
    'dash.main_table': 'Главная таблица',
    'dash.sales_cost_dynamics': 'Динамика продаж и себестоимости',

    // Quick Input
    'qi.title': 'Ввод данных',
    'qi.op.incoming': 'Приход',
    'qi.op.daily': 'Остаток',
    'qi.op.transfer': 'Перевод',
    'qi.op.sale': 'Продажа',
    'qi.date': 'Дата',
    'qi.kitchen': 'Кухня',
    'qi.from_kitchen': 'Из кухни',
    'qi.to_kitchen': 'В кухню',
    'qi.product': 'Продукт',
    'qi.product_ph': 'Сканируйте или введите имя...',
    'qi.qty': 'Количество',
    'qi.balance': 'Баланс',
    'qi.price': 'Цена за ед.',
    'qi.revenue': 'Цена (ед.)',
    'qi.total_calc': 'Итого',
    'qi.save': 'Сохранить',
    'qi.history': 'Недавняя история',
    'qi.search_ph': 'Поиск продукта...',
    'qi.all_types': 'Все типы',
    'qi.all_kitchens': 'Все кухни',
    'qi.not_found': 'Не найдено',
    'qi.no_history': 'История не найдена по фильтрам.',
    'qi.unit': 'Ед.',
    'qi.total_count': 'Всего записей',
    'qi.total_amount': 'Итого сумма',

    // Kitchens
    'kit.add': 'Добавить кухню',
    'kit.search_ph': 'Поиск кухни...',
    'kit.name': 'Название кухни',
    'kit.status': 'Статус',
    'kit.actions': 'Действия',
    'kit.active': 'Активен',
    'kit.inactive': 'Неактивен',
    'kit.no_data': 'Кухни не найдены.',
    'kit.modal.edit': 'Редактировать кухню',
    'kit.modal.add': 'Новая кухня',
    'kit.modal.status_label': 'Статус работы',
    'kit.modal.status_desc': 'Включить или отключить эту точку',
    'kit.create': 'Создать',
    'kit.update': 'Обновить',
    'kit.delete_confirm': 'Вы уверены, что хотите удалить эту кухню?',

    // Products
    'prod.add': 'Добавить продукт',
    'prod.search_ph': 'Поиск по имени или коду...',
    'prod.code': 'Код',
    'prod.name': 'Название',
    'prod.category': 'Категория',
    'prod.unit': 'Ед. изм.',
    'prod.no_data': 'Продукты не найдены.',
    'prod.modal.edit': 'Редактировать продукт',
    'prod.modal.add': 'Новый продукт',
    'prod.create': 'Создать',
    'prod.update': 'Обновить',
    'prod.delete_title': 'Удалить продукт',
    'prod.delete_confirm': 'Удалить продукт? История операций сохранится.',
    'prod.cat.all': 'Все',

    // Analytics
    'anl.kitchen_branch': 'Кухня / Филиал',
    'anl.apply': 'Применить',
    'anl.export': 'Экспорт Excel',
    'anl.dept_analytics': 'Аналитика отделов',
    'anl.sales_dynamics': 'Динамика продаж',
    'anl.col.dept': 'Отд',
    'anl.col.start': 'Нач',
    'anl.col.in': 'Прих',
    'anl.col.exp': 'Расх',
    'anl.col.end': 'Кон',
    'anl.col.sales': 'Прод(сум)',
    'anl.col.mrk': 'Нац(сум)',
    'anl.col.trns': 'Пер',
    'anl.col.trns_in': 'Пер(Прих)',
    'anl.col.trns_out': 'Пер(Расх)',
    'anl.total': 'ИТОГО',
    'anl.date_from': 'Дата с',
    'anl.date_to': 'Дата по',

    // Reports
    'rep.title': 'Отчет по остаткам',
    'rep.col.code': 'Код',
    'rep.col.product': 'Продукт',
    'rep.col.incoming': 'Приход',
    'rep.col.sales': 'Продажи',
    'rep.col.transfer': 'Переводы (Нетто)',
    'rep.col.balance': 'Текущий остаток',
    'rep.no_data': 'Данных за этот период не найдено.',
    'rep.qty': 'Кол-во',
    'rep.sum': 'Сумма',

    // Login
    'auth.welcome': 'С возвращением',
    'auth.subtitle': 'MARGA MENEGER',
    'auth.username': 'Имя пользователя',
    'auth.password': 'Пароль',
    'auth.signin': 'Войти',
    'auth.error': 'Неверные данные. Попробуйте admin / admin123',
    'auth.creds': 'Доступы по умолчанию:',

    // SaaS
    'saas.plan.basic': 'Базовый тариф',
    'saas.plan.pro': 'Про тариф',
    'saas.limit_reached': 'Лимит кухонь исчерпан',
    'saas.limit_desc': 'На Базовом тарифе доступна только 1 кухня.',
    'saas.upgrade_title': 'Обновитесь до Про',
    'saas.upgrade_desc': 'Получите безлимитное количество кухонь с тарифом Про.',
    'saas.upgrade_btn': 'Перейти на Про',
    'saas.current_usage': 'Использовано',
    'saas.unlimited': 'Безлимит',
    'saas.basic_features': 'Лимит: 1 кухня',
    'saas.pro_features': 'Безлимитные кухни',

    // Settings & Billing
    'set.title': 'Настройки',
    'set.tab.general': 'Общие',
    'set.tab.users': 'Сотрудники',
    'set.tab.billing': 'Тарифы и Оплата',
    'set.users.add': 'Добавить сотрудника',
    'set.users.role': 'Роль',
    'set.users.role.admin': 'Менеджер (Админ)',
    'set.users.role.kitchen': 'Повар (Кухня)',
    'set.users.fullname': 'ФИО',
    'set.users.username': 'Логин',
    'set.users.password': 'Пароль',
    'set.users.delete_confirm': 'Вы уверены, что хотите удалить сотрудника?',
    'set.users.limit': 'Лимит сотрудников исчерпан',
    'set.users.desc': 'Управляйте доступом сотрудников к вашей организации.',
    
    // Settings General
    'set.gen.profile': 'Профиль организации',
    'set.gen.org_name': 'Название организации',
    'set.gen.phone': 'Телефон',
    'set.gen.email': 'Email',
    'set.gen.address': 'Адрес',
    'set.gen.finance': 'Финансы и Регион',
    'set.gen.currency': 'Валюта',
    'set.gen.tax': 'Налог (%)',
    'set.gen.inventory': 'Правила инвентаризации',
    'set.gen.low_stock': 'Порог низкого запаса',
    'set.gen.save': 'Сохранить',
    'set.gen.saved': 'Настройки сохранены',

    // Billing
    'bill.current': 'Текущий тариф',
    'bill.cycle': '/ мес',
    'bill.feature.kitchens': 'Кухни',
    'bill.feature.users': 'Пользователи',
    'bill.feature.analytics': 'Расширенная аналитика',
    'bill.feature.support': 'Приоритетная поддержка',
    'bill.btn.upgrade': 'Улучшить',
    'bill.btn.downgrade': 'Понизить',
    'bill.btn.current': 'Ваш тариф',
    'bill.modal.title': 'Подтверждение смены тарифа',
    'bill.modal.desc': 'Вы собираетесь изменить тариф подписки.',
    'bill.modal.new_plan': 'Новый тариф',
    'bill.modal.price': 'Цена',
    'bill.modal.total': 'Итого к оплате',
    'bill.modal.confirm': 'Оплатить и перейти',
    'bill.modal.processing': 'Обработка...',

    // Common
    'common.show': 'Показать',
    'common.entries': 'записей',
    'common.prev': 'Назад',
    'common.next': 'Вперед',

    // Chart
    'dash.chart.daily': 'День',
    'dash.chart.cumulative': 'Накопительный',
    'dash.chart.sales': 'Продажи',
    'dash.chart.cost': 'Расходы',
    'dash.chart.cum_sales': 'Накоп. Продажи',
    'dash.chart.cum_cost': 'Накоп. Расходы',
    'dash.chart.product': 'По продуктам',
    'dash.chart.prod_expense': 'Расход продукта',
  },
  uz: {
    // Navigation & Layout
    'nav.dashboard': 'Bosh sahifa',
    'nav.analytics': 'Tahlil',
    'nav.quick_input': 'Ma\'lumot kiritish',
    'nav.kitchens': 'Oshxonalar',
    'nav.products': 'Mahsulotlar',
    'nav.reports': 'Hisobotlar',
    'nav.settings': 'Sozlamalar',
    'nav.logout': 'Chiqish',
    'nav.main_menu': 'Asosiy menyu',
    'nav.explore': 'Boshqalar',
    'header.greeting': 'Xayrli kun, Shef',
    'header.role': 'Bosh oshpaz',

    // Dashboard
    'dash.total_revenue': 'Jami tushum',
    'dash.revenue_period': 'Davr tushumi',
    'dash.incoming_vol': 'Kirim hajmi',
    'dash.units_received': 'Qabul qilingan birliklar',
    'dash.sales_count': 'Sotuvlar soni',
    'dash.transactions': 'Tranzaksiyalar',
    'dash.operations': 'Operatsiyalar',
    'dash.total_events': 'Jami yozuvlar',
    'dash.trends': 'Tranzaksiya tendentsiyalari',
    'dash.profit_summary': 'Foyda hisoboti',
    'dash.see_details': 'Batafsil',
    'dash.yearly_profit': 'Yillik loyiha foydasi',
    'dash.weekly_profit': 'Haftalik loyiha foydasi',
    'dash.filter.daily': 'Kunlik',
    'dash.filter.monthly': 'Oylik',
    'dash.filter.all_kitchens': 'Barcha oshxonalar',
    'dash.avg_yearly': 'O\'rtacha yillik',
    'dash.avg_monthly': 'O\'rtacha oylik',
    'dash.from': 'Dan',
    'dash.main_table': 'Asosiy jadval',
    'dash.sales_cost_dynamics': 'Sotish va tannarx dinamikasi',

    // Quick Input
    'qi.title': 'Ma\'lumot kiritish',
    'qi.op.incoming': 'Kirim',
    'qi.op.daily': 'Qoldiq',
    'qi.op.transfer': 'O\'tkazma',
    'qi.op.sale': 'Sotish',
    'qi.date': 'Sana',
    'qi.kitchen': 'Oshxona',
    'qi.from_kitchen': 'Oshxonadan',
    'qi.to_kitchen': 'Oshxonaga',
    'qi.product': 'Mahsulot',
    'qi.product_ph': 'Kod yoki nomni skanerlang...',
    'qi.qty': 'Miqdor',
    'qi.balance': 'Balans',
    'qi.price': 'Birlik narxi',
    'qi.revenue': 'Tushum (Birlik)',
    'qi.total_calc': 'Jami',
    'qi.save': 'Saqlash',
    'qi.history': 'Yaqinda kiritilganlar',
    'qi.search_ph': 'Mahsulotni qidirish...',
    'qi.all_types': 'Barcha turlar',
    'qi.all_kitchens': 'Barcha oshxonalar',
    'qi.not_found': 'Topilmadi',
    'qi.no_history': 'Filtrlar bo\'yicha tarix topilmadi.',
    'qi.unit': 'Birlik',
    'qi.total_count': 'Jami yozuvlar',
    'qi.total_amount': 'Jami summa',

    // Kitchens
    'kit.add': 'Oshxona qo\'shish',
    'kit.search_ph': 'Oshxona qidirish...',
    'kit.name': 'Oshxona nomi',
    'kit.status': 'Holat',
    'kit.actions': 'Amallar',
    'kit.active': 'Faol',
    'kit.inactive': 'Faol emas',
    'kit.no_data': 'Mezonlarga mos oshxonalar topilmadi.',
    'kit.modal.edit': 'Oshxonani tahrirlash',
    'kit.modal.add': 'Yangi oshxona qo\'shish',
    'kit.modal.status_label': 'Ishlash holati',
    'kit.modal.status_desc': 'Ushbu oshxona joylashuvini yoqish yoki o\'chirish',
    'kit.create': 'Oshxona yaratish',
    'kit.update': 'Oshxonani yangilash',
    'kit.delete_confirm': 'Ushbu oshxonani o\'chirishni xohlaysizmi?',

    // Products
    'prod.add': 'Mahsulot qo\'shish',
    'prod.search_ph': 'Mahsulot nomi yoki kodi bo\'yicha qidirish...',
    'prod.code': 'Kod',
    'prod.name': 'Mahsulot nomi',
    'prod.category': 'Toifa',
    'prod.unit': 'Birlik',
    'prod.no_data': 'Mahsulotlar topilmadi.',
    'prod.modal.edit': 'Mahsulotni tahrirlash',
    'prod.modal.add': 'Yangi mahsulot qo\'shish',
    'prod.create': 'Mahsulot yaratish',
    'prod.update': 'Mahsulotni yangilash',
    'prod.delete_title': 'Mahsulotni o\'chirish',
    'prod.delete_confirm': 'Ushbu mahsulotni o\'chirasizmi? Operatsiyalar tarixi saqlanib qoladi.',
    'prod.cat.all': 'Barchasi',

    // Analytics
    'anl.kitchen_branch': 'Oshxona / Filial',
    'anl.apply': 'Filtrlarni qo\'llash',
    'anl.export': 'Excelga eksport',
    'anl.dept_analytics': 'Bo\'lim tahlili',
    'anl.sales_dynamics': 'Sotuv dinamikasi',
    'anl.col.dept': 'Bo\'lim',
    'anl.col.start': 'Bosh',
    'anl.col.in': 'Kir',
    'anl.col.exp': 'Chiq',
    'anl.col.end': 'Oxir',
    'anl.col.sales': 'Sotuv(sum)',
    'anl.col.mrk': 'Foyda(sum)',
    'anl.col.trns': 'O\'tk',
    'anl.col.trns_in': 'O\'tk(Kir)',
    'anl.col.trns_out': 'O\'tk(Chiq)',
    'anl.total': 'JAMI',
    'anl.date_from': 'Sana dan',
    'anl.date_to': 'Sana gacha',

    // Reports
    'rep.title': 'Inventar balansi hisoboti',
    'rep.col.code': 'Kod',
    'rep.col.product': 'Mahsulot nomi',
    'rep.col.incoming': 'Kirim',
    'rep.col.sales': 'Sotuv',
    'rep.col.transfer': 'O\'tkazma (Netto)',
    'rep.col.balance': 'Joriy balans',
    'rep.no_data': 'Ushbu davr uchun ma\'lumot topilmadi.',
    'rep.qty': 'Miqd',
    'rep.sum': 'Sum',

    // Login
    'auth.welcome': 'Xush kelibsiz',
    'auth.subtitle': 'MARGA MENEGER',
    'auth.username': 'Foydalanuvchi nomi',
    'auth.password': 'Parol',
    'auth.signin': 'Kirish',
    'auth.error': 'Noto\'g\'ri ma\'lumotlar. admin / admin123 ni sinab ko\'ring',
    'auth.creds': 'Standart hisob ma\'lumotlari:',

    // SaaS
    'saas.plan.basic': 'Basic rejasi',
    'saas.plan.pro': 'Pro rejasi',
    'saas.limit_reached': 'Oshxona chekloviga yetdi',
    'saas.limit_desc': 'Basic rejasida 1 ta oshxona limiti mavjud.',
    'saas.upgrade_title': 'Pro ga o\'tish',
    'saas.upgrade_desc': 'Pro rejasi bilan cheksiz oshxonalar va kengaytirilgan xususiyatlarga ega bo\'ling.',
    'saas.upgrade_btn': 'Pro ga o\'tish',
    'saas.current_usage': 'Foydalanish',
    'saas.unlimited': 'Cheksiz',
    'saas.basic_features': '1 ta oshxona limiti',
    'saas.pro_features': 'Cheksiz oshxonalar',

    // Settings & Billing
    'set.title': 'Sozlamalar',
    'set.tab.general': 'Umumiy',
    'set.tab.users': 'Jamoa a\'zolari',
    'set.tab.billing': 'Rejalar va to\'lov',
    'set.users.add': 'A\'zo qo\'shish',
    'set.users.role': 'Rol',
    'set.users.role.admin': 'Menejer (Admin)',
    'set.users.role.kitchen': 'Oshxona xodimi',
    'set.users.fullname': 'To\'liq ism',
    'set.users.username': 'Foydalanuvchi nomi',
    'set.users.password': 'Parol',
    'set.users.delete_confirm': 'Ushbu foydalanuvchini o\'chirishni xohlaysizmi?',
    'set.users.limit': 'Foydalanuvchi limiti yetdi',
    'set.users.desc': 'Tashkilotingiz ish joyiga kim kirishini boshqaring.',
    
    // Settings General
    'set.gen.profile': 'Tashkilot profili',
    'set.gen.org_name': 'Tashkilot nomi',
    'set.gen.phone': 'Telefon raqami',
    'set.gen.email': 'Email manzili',
    'set.gen.address': 'Manzil',
    'set.gen.finance': 'Moliya va Hudud',
    'set.gen.currency': 'Valyuta',
    'set.gen.tax': 'Soliq (%)',
    'set.gen.inventory': 'Ombor qoidalari',
    'set.gen.low_stock': 'Kam qoldiq chegarasi',
    'set.gen.save': 'Saqlash',
    'set.gen.saved': 'Sozlamalar saqlandi',

    // Billing
    'bill.current': 'Joriy tarif',
    'bill.cycle': '/ oy',
    'bill.feature.kitchens': 'Oshxonalar',
    'bill.feature.users': 'Foydalanuvchilar',
    'bill.feature.analytics': 'Kengaytirilgan tahlil',
    'bill.feature.support': 'Tezkor yordam',
    'bill.btn.upgrade': 'Kuchaytirish',
    'bill.btn.downgrade': 'Pasaytirish',
    'bill.btn.current': 'Sizning tarifingiz',
    'bill.modal.title': 'Tarifni o\'zgartirishni tasdiqlash',
    'bill.modal.desc': 'Siz obuna tarifingizni o\'zgartirmoqchisiz.',
    'bill.modal.new_plan': 'Yangi tarif',
    'bill.modal.price': 'Narx',
    'bill.modal.total': 'Bugungi to\'lov',
    'bill.modal.confirm': 'To\'lash va o\'tish',
    'bill.modal.processing': 'Qayta ishlanmoqda...',

    // Common
    'common.show': 'Ko\'rsatish',
    'common.entries': 'yozuvlar',
    'common.prev': 'Oldingi',
    'common.next': 'Keyingi',

    // Chart
    'dash.chart.daily': 'Kunlik',
    'dash.chart.cumulative': 'Yig\'indili',
    'dash.chart.sales': 'Sotuv',
    'dash.chart.cost': 'Xarajat',
    'dash.chart.cum_sales': 'Jami Sotuv',
    'dash.chart.cum_cost': 'Jami Xarajat',
    'dash.chart.product': 'Mahsulotlar bo\'yicha',
    'dash.chart.prod_expense': 'Mahsulot xarajati',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('km_lang') as Language) || 'uz';
  });

  useEffect(() => {
    localStorage.setItem('km_lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
