# Generated by Django 6.0.3 on 2026-03-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchens', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INCOMING', 'Приход'), ('DAILY', 'Ежедневный расход'), ('TRANSFER', 'Перемещение'), ('SALE', 'Продажа')], max_length=20, verbose_name='Тип операции')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='kitchens.kitchen', verbose_name='Кухня')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization', verbose_name='Организация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='products.product', verbose_name='Продукт')),
                ('to_kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='kitchens.kitchen', verbose_name='Кухня-получатель')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date'], name='operations__date_1b0524_idx'), models.Index(fields=['kitchen'], name='operations__kitchen_a5e2d4_idx'), models.Index(fields=['product'], name='operations__product_2e766f_idx'), models.Index(fields=['type'], name='operations__type_3a028d_idx'), models.Index(fields=['organization', 'date'], name='operations__organiz_9e6b6e_idx')],
            },
        ),
    ]
