# Generated by Django 6.0.3 on 2026-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
        ('operations', '0002_alter_operationentry_product'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operationentry',
            index=models.Index(fields=['organization', 'kitchen', 'date'], name='operations__organiz_a1b6f1_idx'),
        ),
    ]
