# Generated by Django 6.0.3 on 2026-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operationentry_operations__organiz_a1b6f1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Удалено в'),
        ),
    ]
