# Generated by Django 6.0.3 on 2026-07-23 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('RESOLVED', 'Обработана')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана в')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто обработал')),
            ],
            options={
                'verbose_name': 'Заявка на сброс пароля',
                'verbose_name_plural': 'Заявки на сброс пароля',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounts_pa_status_c8e36a_idx')],
            },
        ),
    ]
