# Generated by Django 6.0.3 on 2026-06-01 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_plan', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=20, verbose_name='Целевой план')),
                ('amount', models.BigIntegerField(verbose_name='Сумма (тийин)')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAYING', 'В процессе оплаты'), ('PAID', 'Оплачен'), ('CANCELLED', 'Отменён'), ('EXPIRED', 'Истёк')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен в')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён в')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Заказ на подписку',
                'verbose_name_plural': 'Заказы на подписку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payme_id', models.CharField(max_length=255, unique=True, verbose_name='ID транзакции Payme')),
                ('state', models.IntegerField(verbose_name='Состояние')),
                ('amount', models.BigIntegerField(verbose_name='Сумма (тийин)')),
                ('reason', models.SmallIntegerField(blank=True, null=True, verbose_name='Причина отмены')),
                ('payme_time', models.BigIntegerField(default=0, verbose_name='Время создания (Payme, мс)')),
                ('payme_create_time', models.BigIntegerField(default=0, verbose_name='Время создания у нас (мс)')),
                ('payme_perform_time', models.BigIntegerField(default=0, verbose_name='Время проведения (мс)')),
                ('payme_cancel_time', models.BigIntegerField(default=0, verbose_name='Время отмены (мс)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='payments.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Транзакция Payme',
                'verbose_name_plural': 'Транзакции Payme',
                'ordering': ['-created_at'],
            },
        ),
    ]
