# Generated by Django 6.0.3 on 2026-06-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True, verbose_name='План')),
                ('price', models.BigIntegerField(help_text='Цена в тийинах (1 UZS = 100 тийин). BASIC = 0 (бесплатно).', verbose_name='Цена (тийин)')),
                ('max_kitchens', models.PositiveIntegerField(verbose_name='Макс. кухонь')),
                ('max_users', models.PositiveIntegerField(verbose_name='Макс. пользователей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тариф (PlanConfig)',
                'verbose_name_plural': 'Тарифы (PlanConfig)',
                'ordering': ['plan'],
            },
        ),
    ]
