# Generated by Django 6.0.3 on 2026-06-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_seed_planconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_plan',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Предыдущий план'),
        ),
    ]
