# Generated by Django 6.0.3 on 2026-06-09 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('payments', '0004_order_previous_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ORDER_STATE_CHANGE', 'Изменение статуса заказа'), ('TXN_STATE_CHANGE', 'Изменение статуса транзакции'), ('PLAN_CHANGE', 'Смена плана'), ('PLAN_REVERT', 'Откат плана')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.BigIntegerField()),
                ('old_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Аудит-лог',
                'verbose_name_plural': 'Аудит-логи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='payments_au_event_t_37d325_idx'), models.Index(fields=['organization', 'created_at'], name='payments_au_organiz_520165_idx')],
            },
        ),
    ]
