# Generated by Django 6.0.3 on 2026-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('ORDER_STATE_CHANGE', 'Изменение статуса заказа'), ('TXN_STATE_CHANGE', 'Изменение статуса транзакции'), ('PLAN_CHANGE', 'Смена плана'), ('PLAN_REVERT', 'Откат плана'), ('USER_CREATED', 'Создан пользователь'), ('USER_UPDATED', 'Обновлён пользователь'), ('USER_DELETED', 'Удалён пользователь'), ('KITCHEN_CREATED', 'Создана кухня'), ('KITCHEN_UPDATED', 'Обновлена кухня'), ('KITCHEN_DELETED', 'Удалена кухня'), ('PRODUCT_CREATED', 'Создан продукт'), ('PRODUCT_UPDATED', 'Обновлён продукт'), ('PRODUCT_DELETED', 'Удалён продукт'), ('ORG_SUSPENDED', 'Организация приостановлена'), ('ORG_UNSUSPENDED', 'Организация активирована'), ('ORG_DELETED', 'Организация удалена')], max_length=50),
        ),
    ]
