# Generated by Django 6.0.3 on 2026-03-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('plan', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20, verbose_name='Тарифный план')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('max_kitchens', models.PositiveIntegerField(default=3, verbose_name='Макс. кухонь')),
                ('max_users', models.PositiveIntegerField(default=10, verbose_name='Макс. пользователей')),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MRR')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Валюта')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка налога (%)')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, verbose_name='Порог низкого запаса')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-created_at'],
            },
        ),
    ]
