# Generated by Django 6.0.3 on 2026-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка истекает'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка начата'),
        ),
    ]
