# Generated by Django 6.0.3 on 2026-06-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_plan_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Удалено в'),
        ),
    ]
